import {parseRosterCsv,rosterChanges} from './roster.js';
import {teacherStore} from './teacher-store.js';
import {submissionOverview} from './teacher-model.js';
import {isChallenge,roundLabel} from './progress.js';
import {resultItems} from './progress.js';
import {DOMAINS,grade,parseCsv,toCsv,normalizeName,validStudent} from './core.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=new Map(),roster=new Map(),catalog;const banks=new Map();
let rosterPreview=null;
async function readFixedRoster(hash){const response=await fetch('api/admin/roster-file'+(hash?'?fileHash='+encodeURIComponent(hash):''));let data;try{data=await response.json();}catch{throw new Error('学校サーバPCの http://localhost:3000/admin.html から名簿を確認してください。');}if(!response.ok)throw new Error(data.error??'名簿を読み込めません。');return data;}
$('roster-check').onclick=async()=>{rosterPreview=null;$('roster-import').disabled=true;try{const data=await readFixedRoster(),changes=rosterChanges([...roster].map(([code,name])=>({code,name})),data.rows);rosterPreview=data;$('roster-preview').textContent=`meibo.csv：${data.rows.length}名。追加 ${changes.added}名・氏名変更 ${changes.changed}名・名簿から除外 ${changes.removed}名。成績は削除しません。`;$('roster-import').disabled=false;}catch(e){$('roster-preview').textContent=e.message;}};
$('roster-import').onclick=async()=>{if(!rosterPreview||!confirm('確認した名簿で、この教員ブラウザの名簿を置き換えますか？成績と元CSVは変更しません。'))return;try{const data=await readFixedRoster(rosterPreview.fileHash);await teacherStore.saveRoster(data.rows);roster=new Map(data.rows.map(r=>[r.code,r.name]));$('roster-preview').textContent=`名簿${data.rows.length}名を取り込みました。`;rosterPreview=null;$('roster-import').disabled=true;render();}catch(e){rosterPreview=null;$('roster-import').disabled=true;$('roster-preview').textContent=e.message;}};
async function bank(id){if(banks.has(id))return banks.get(id);const r=await fetch(`data/${id}.json`);if(!r.ok)throw new Error('問題データを取得できません。');const x=await r.json();banks.set(id,x.questions);return x.questions;}
async function validate(r){if(!r||r.app!=='info1_IPass'||r.schemaVersion!==1||!validStudent(r.studentCode,r.studentName)||!/^[0-9a-f-]{36}$/i.test(r.attemptId)||!Array.isArray(r.answers)||r.answers.length<1||r.answers.length>1500||!Number.isFinite(Date.parse(r.finishedAt)))throw new Error('結果JSONの形式が正しくありません。');const ids=[...new Set(r.answers.map(a=>String(a.id).slice(0,String(a.id).lastIndexOf('-'))))];if(ids.some(id=>!catalog.exams.some(e=>e.id===id)))throw new Error('収録していない問題IDがあります。');const questions=(await Promise.all(ids.map(bank))).flat();const byId=new Map(questions.map(q=>[q.id,q]));const picked={},selected=[];for(const a of r.answers){if(!byId.has(a.id)||selected.some(q=>q.id===a.id)||!Number.isInteger(a.picked)||a.picked < -1 || a.picked>3)throw new Error('解答データが正しくありません。');selected.push(byId.get(a.id));if(a.picked>=0)picked[a.id]=a.picked;}return {...r,...grade(selected,picked)};}
function match(r){if(!roster.size)return '名簿未読込';const n=roster.get(r.studentCode);return n===undefined?'番号なし':normalizeName(n)===normalizeName(r.studentName)?'一致':`氏名不一致（${n}）`;}
function render(){renderSubmissions();const a=[...records.values()].sort((a,b)=>a.studentCode.localeCompare(b.studentCode)||a.finishedAt.localeCompare(b.finishedAt));const completed=a.filter(r=>isChallenge(r)&&!r.abandoned);$('stats').innerHTML=`<div class="stat">受験件数<strong>${a.length}</strong></div><div class="stat">受験者数<strong>${new Set(a.map(x=>x.studentCode)).size}</strong></div><div class="stat">本チャレンジ平均<strong>${completed.length?Math.round(completed.reduce((s,x)=>s+x.score,0)/completed.length):0}%</strong></div>`;$('records').innerHTML=a.map(r=>`<tr><td>${esc(r.studentCode)}</td><td>${esc(r.studentName)}</td><td>${esc(roundLabel(r))}</td><td>${r.abandoned?'中断終了':'終了'}</td><td>${esc(match(r))}</td><td>${esc(r.title)}</td><td>${r.correct}/${r.total}</td><td>${r.score}%</td>${DOMAINS.map(d=>`<td>${r.byDomain.find(x=>x.domain===d)?.rate??'—'}${r.byDomain.find(x=>x.domain===d)?.rate==null?'':'%'}</td>`).join('')}<td>${esc(new Date(r.finishedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}))}</td></tr>`).join('');}
$('result-files').onchange=async e=>{let added=0,failed=[];for(const file of e.target.files){try{const packet=JSON.parse(await file.text());for(const item of resultItems(packet)){const r=await validate(item);if(!records.has(r.attemptId)){records.set(r.attemptId,r);added++;}}}catch(err){failed.push(file.name+': '+err.message);}}$('admin-status').textContent=`${added}件を追加しました。${failed.length?'\n'+failed.join('\n'):''}`;await teacherStore.saveRecords([...records.values()]);render();e.target.value='';};
$('roster-file').onchange=async e=>{try{const bytes=await e.target.files[0].arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{text=new TextDecoder('shift_jis').decode(bytes);}const next=new Map(parseRosterCsv(text).map(row=>[row.code,row.name]));roster=next;await teacherStore.saveRoster([...roster].map(([code,name])=>({code,name})));$('admin-status').textContent=`名簿${roster.size}名を読み込みました。`;render();}catch(err){$('admin-status').textContent=err.message;}e.target.value='';};
$('clear').onclick=async()=>{if(confirm('この教員端末に取り込んだ成績を削除しますか？名簿・学校サーバ・元の提出ファイルは削除されません。')){await teacherStore.clearRecords();records.clear();render();}};
$('export').onclick=()=>{const rows=[['受験番号','氏名','実施回','中断終了','名簿照合','試験','正解数','問題数','得点率','ストラテジ正答率','マネジメント正答率','テクノロジ正答率','開始日時','終了日時','所要秒数','時間終了','受験ID'],...[...records.values()].map(r=>[r.studentCode,r.studentName,roundLabel(r),r.abandoned?'はい':'いいえ',match(r),r.title,r.correct,r.total,r.score,...DOMAINS.map(d=>r.byDomain.find(x=>x.domain===d)?.rate??''),r.startedAt,r.finishedAt,r.elapsedSeconds,r.timeUp?'はい':'いいえ',r.attemptId])];const url=URL.createObjectURL(new Blob([toCsv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='IPass_results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('server-load').onclick=async()=>{try{const resp=await fetch('api/admin/results');if(!resp.ok)throw new Error('学校サーバPCの http://localhost:3000/admin.html から操作してください。');const rows=await resp.json();for(const row of rows)records.set(row.attemptId,await validate(row));await teacherStore.saveRecords([...records.values()]);$('admin-status').textContent=`${rows.length}件を読み込みました。`;render();}catch(e){$('admin-status').textContent=e.message;}};
$('settings-form').onsubmit=e=>{e.preventDefault();$('settings-error').textContent='';const mode=$('setting-mode').value,year=mode==='school'?'all':$('setting-year').value;if(mode==='year'&&year==='all'){$('settings-error').textContent='年度別模擬試験は、出題年度を1つ選んでください。';return;}const u=new URL('index.html',location.href);u.search=new URLSearchParams({mode,year,domain:mode==='practice'?$('setting-domain').value:'all',count:mode==='school'?'75':mode==='year'?'100':$('setting-count').value,minutes:mode==='school'?'45':mode==='year'?'120':$('setting-minutes').value});$('exam-link').value=u.href;};
try{const r=await fetch('data/catalog.json');if(!r.ok)throw new Error();catalog=await r.json();for(const row of await teacherStore.records())records.set(row.attemptId,row);for(const row of await teacherStore.roster())roster.set(row.code,row.name);$('setting-year').insertAdjacentHTML('beforeend',catalog.exams.map(e=>`<option value="${e.id}">${esc(e.label)}</option>`).join(''));render();}catch{$('admin-status').textContent='問題データを読み込めません。';}

function renderSubmissions(){const rows=submissionOverview([...roster].map(([code,name])=>({code,name})),[...records.values()]),filtered=$('submission-filter').value==='missing'?rows.filter(r=>r.missing):rows;$('submission-count').textContent=roster.size?`名簿 ${rows.length}名 ／ 本チャレンジ未提出 ${rows.filter(r=>r.missing).length}名`:'名簿CSVを読み込むと未提出者を表示します。';$('submission-records').innerHTML=filtered.map(r=>`<tr><td>${esc(r.code)}</td><td>${esc(r.name)}</td><td>${esc(r.status)}${r.mismatches?'（氏名不一致あり）':''}</td><td>${r.complete.length}回終了／${r.abandoned}回中断</td>${[1,2,3,4,5].map(n=>{const a=r.challenge.find(x=>x.round===n);return `<td>${a?(a.abandoned?'中断終了':a.score+'%'):'未提出'}</td>`;}).join('')}<td><a href="compare.html?code=${r.code}">比較</a></td></tr>`).join('')||'<tr><td colspan="10">該当する生徒はいません。</td></tr>';}
$('submission-filter').onchange=renderSubmissions;
$('missing-csv').onclick=()=>{const rows=submissionOverview([...roster].map(([code,name])=>({code,name})),[...records.values()]).filter(r=>r.missing),u=URL.createObjectURL(new Blob([toCsv([['受験番号','氏名','状態'],...rows.map(r=>[r.code,r.name,r.status])])],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='IPass_missing.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
