import {DOMAINS,grade,parseCsv,toCsv,normalizeName,validStudent} from './core.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=new Map(),roster=new Map(),catalog;const banks=new Map();
async function bank(id){if(banks.has(id))return banks.get(id);const r=await fetch(`data/${id}.json`);if(!r.ok)throw new Error('問題データを取得できません。');const x=await r.json();banks.set(id,x.questions);return x.questions;}
async function validate(r){if(!r||r.app!=='info1_IPass'||r.schemaVersion!==1||!validStudent(r.studentCode,r.studentName)||!/^[0-9a-f-]{36}$/i.test(r.attemptId)||!Array.isArray(r.answers)||r.answers.length<1||r.answers.length>1500||!Number.isFinite(Date.parse(r.finishedAt)))throw new Error('結果JSONの形式が正しくありません。');const ids=[...new Set(r.answers.map(a=>String(a.id).slice(0,String(a.id).lastIndexOf('-'))))];if(ids.some(id=>!catalog.exams.some(e=>e.id===id)))throw new Error('収録していない問題IDがあります。');const questions=(await Promise.all(ids.map(bank))).flat();const byId=new Map(questions.map(q=>[q.id,q]));const picked={},selected=[];for(const a of r.answers){if(!byId.has(a.id)||selected.some(q=>q.id===a.id)||!Number.isInteger(a.picked)||a.picked < -1 || a.picked>3)throw new Error('解答データが正しくありません。');selected.push(byId.get(a.id));if(a.picked>=0)picked[a.id]=a.picked;}return {...r,...grade(selected,picked)};}
function match(r){if(!roster.size)return '名簿未読込';const n=roster.get(r.studentCode);return n===undefined?'番号なし':normalizeName(n)===normalizeName(r.studentName)?'一致':`氏名不一致（${n}）`;}
function render(){const a=[...records.values()].sort((a,b)=>a.studentCode.localeCompare(b.studentCode)||a.finishedAt.localeCompare(b.finishedAt));$('stats').innerHTML=`<div class="stat">受験件数<strong>${a.length}</strong></div><div class="stat">受験者数<strong>${new Set(a.map(x=>x.studentCode)).size}</strong></div><div class="stat">平均得点率<strong>${a.length?Math.round(a.reduce((s,x)=>s+x.score,0)/a.length):0}%</strong></div>`;$('records').innerHTML=a.map(r=>`<tr><td>${esc(r.studentCode)}</td><td>${esc(r.studentName)}</td><td>${esc(match(r))}</td><td>${esc(r.title)}</td><td>${r.correct}/${r.total}</td><td>${r.score}%</td>${DOMAINS.map(d=>`<td>${r.byDomain.find(x=>x.domain===d)?.rate??'—'}${r.byDomain.find(x=>x.domain===d)?.rate==null?'':'%'}</td>`).join('')}<td>${esc(new Date(r.finishedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}))}</td></tr>`).join('');}
$('result-files').onchange=async e=>{let added=0,failed=[];for(const file of e.target.files){try{const r=await validate(JSON.parse(await file.text()));if(!records.has(r.attemptId)){records.set(r.attemptId,r);added++;}}catch(err){failed.push(file.name+': '+err.message);}}$('admin-status').textContent=`${added}件を追加しました。${failed.length?'\n'+failed.join('\n'):''}`;render();e.target.value='';};
$('roster-file').onchange=async e=>{try{const bytes=await e.target.files[0].arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{text=new TextDecoder('shift_jis').decode(bytes);}const next=new Map();for(const row of parseCsv(text.replace(/^\ufeff/,''))){const code=String(row[0]??'').trim(),name=normalizeName(row[1]??'');if(!/^\d{4}$/.test(code))continue;if(!name)throw new Error('名簿に空欄の氏名があります。');if(next.has(code))throw new Error(`番号${code}が重複しています。`);next.set(code,name);}if(!next.size)throw new Error('4桁番号を含む名簿データがありません。');roster=next;$('admin-status').textContent=`名簿${roster.size}名を読み込みました。`;render();}catch(err){$('admin-status').textContent=err.message;}e.target.value='';};
$('clear').onclick=()=>{if(confirm('表示中の集計をクリアしますか？学校サーバや元の提出ファイルは削除されません。')){records.clear();render();}};
$('export').onclick=()=>{const rows=[['受験番号','氏名','名簿照合','試験','正解数','問題数','得点率','ストラテジ正答率','マネジメント正答率','テクノロジ正答率','開始日時','終了日時','所要秒数','時間終了','受験ID'],...[...records.values()].map(r=>[r.studentCode,r.studentName,match(r),r.title,r.correct,r.total,r.score,...DOMAINS.map(d=>r.byDomain.find(x=>x.domain===d)?.rate??''),r.startedAt,r.finishedAt,r.elapsedSeconds,r.timeUp?'はい':'いいえ',r.attemptId])];const url=URL.createObjectURL(new Blob([toCsv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='IPass_results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('server-load').onclick=async()=>{try{const resp=await fetch('api/admin/results');if(!resp.ok)throw new Error('学校サーバPCの http://localhost:3000/admin.html から操作してください。');const rows=await resp.json();for(const row of rows)records.set(row.attemptId,await validate(row));$('admin-status').textContent=`${rows.length}件を読み込みました。`;render();}catch(e){$('admin-status').textContent=e.message;}};
$('settings-form').onsubmit=e=>{e.preventDefault();$('settings-error').textContent='';const mode=$('setting-mode').value,year=$('setting-year').value;if(mode==='year'&&year==='all'){$('settings-error').textContent='年度別模擬試験は、出題年度を1つ選んでください。';return;}const u=new URL('index.html',location.href);u.search=new URLSearchParams({mode,year,domain:mode==='year'?'all':$('setting-domain').value,count:$('setting-count').value,minutes:$('setting-minutes').value});$('exam-link').value=u.href;};
try{const r=await fetch('data/catalog.json');if(!r.ok)throw new Error();catalog=await r.json();$('setting-year').insertAdjacentHTML('beforeend',catalog.exams.map(e=>`<option value="${e.id}">${esc(e.label)}</option>`).join(''));render();}catch{$('admin-status').textContent='問題データを読み込めません。';}
