import {teacherStore} from './teacher-store.js';
import {classSummary,questionSummary} from './analytics-model.js';
import {DOMAINS,toCsv,normalizeName} from './core.js';
import {comparisonKey,comparisonLabel} from './progress.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(rows,name){const u=URL.createObjectURL(new Blob([toCsv(rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
let records=[],roster=[],classes=[],questions=[];
function render(){classes=classSummary(roster,records);$('class-rows').innerHTML=classes.map(c=>`<tr><td>${esc(c.classCode)}</td><td>${c.enrolled}</td><td>${c.submitted} (${Math.round(c.submitted/c.enrolled*100)}%)</td><td>${c.completed5}</td><td>${c.latestAverage??'—'} (${c.latestCount}人)</td><td>${c.averageGain??'—'} (${c.gainCount}人)</td>${c.byDomain.map(d=>`<td>${d.rate??'—'} (${d.count}人)</td>`).join('')}</tr>`).join('')||'<tr><td colspan="9">名簿を管理画面で取り込んでください。</td></tr>';const known=new Map(roster.map(p=>[p.code,normalizeName(p.name)])),matched=roster.length?records.filter(r=>known.get(r.studentCode)===normalizeName(r.studentName)):records;questions=questionSummary(matched,{mode:$('question-mode').value,classCode:$('question-class').value,round:$('question-round').value,group:$('question-group').value});$('question-rows').innerHTML=questions.map(q=>`<tr><td>${esc(q.id)}<br><small>${esc(q.source)}</small></td><td>${esc(q.domain)}</td><td>${q.total}</td><td>${q.students}</td><td>${q.correct}</td><td>${q.rate}%</td><td>${q.unanswered}</td><td>${q.choices.join(' / ')}</td></tr>`).join('')||'<tr><td colspan="8">対象記録はありません。</td></tr>';}
for(const id of ['question-mode','question-class','question-round','question-group'])$(id).onchange=render;
$('class-csv').onclick=()=>download([['クラス','名簿人数','提出者','5回終了','最新平均','最新平均人数','平均伸び','伸び人数',...DOMAINS],...classes.map(c=>[c.classCode,c.enrolled,c.submitted,c.completed5,c.latestAverage??'',c.latestCount,c.averageGain??'',c.gainCount,...c.byDomain.map(d=>d.rate??'')])],'IPass_classes.csv');
$('question-csv').onclick=()=>download([['問題ID','出典','分野','解答件数','人数','正解','正答率','未解答','ア','イ','ウ','エ'],...questions.map(q=>[q.id,q.source,q.domain,q.total,q.students,q.correct,q.rate,q.unanswered,...q.choices])],'IPass_questions.csv');
$('reports-load').onclick=async()=>{try{const resp=await fetch('api/admin/reports');if(!resp.ok)throw new Error('学校サーバPCの管理画面から操作してください。');const reports=await resp.json();$('report-rows').innerHTML=reports.map(r=>`<tr><td>${esc(r.studentCode)} ${esc(r.studentName)}</td><td>${esc(r.questionId)}</td><td>${esc(r.kind)}<br>${esc(r.text)}</td><td>${esc(new Date(r.createdAt).toLocaleString('ja-JP'))}</td><td><select data-report="${esc(r.reportId)}">${['未確認','確認中','対応済み'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="5">報告なし</td></tr>';document.querySelectorAll('[data-report]').forEach(el=>el.onchange=async()=>{try{const resp=await fetch('api/admin/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reportId:el.dataset.report,status:el.value})});if(!resp.ok)throw new Error('確認状態を保存できません。');$('reports-message').textContent='確認状態を保存しました。';}catch(e){$('reports-message').textContent=e.message;}});}catch(e){$('reports-message').textContent=e.message;}};
try{records=await teacherStore.records();roster=await teacherStore.roster();$('question-class').insertAdjacentHTML('beforeend',[...new Set(roster.map(p=>p.code.slice(0,2)))].sort().map(c=>`<option>${esc(c)}</option>`).join(''));const groups=new Map(records.map(r=>[comparisonKey(r),comparisonLabel(r)]));$('question-group').insertAdjacentHTML('beforeend',[...groups].map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join(''));render();}catch(e){$('analytics-message').textContent=e.message;}
