import {StudentStore} from './student-store.js';
import {createStatus} from './status.js';
import {DOMAINS,LABELS,normalizeName,validStudent,remainingSeconds,clock,selectQuestions,grade,advice} from './core.js';
const $=id=>document.getElementById(id), body=$('exam-body');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='ipass:active:v1',VIEW='ipass:view:v1',HISTORY='ipass:history:v1';
let catalog,bank=[],session=null,phase='entry',guidePage=0,reviewFilter='wrong',busy=false;
let view={bg:'#fffdf4',ink:'#17263c',zoom:100};
let downloaded=new Map(), confirmAction=null,archive=false;
const store=new StudentStore();
const status=createStatus(store,{screen,openAttempt,loadQuestions});
async function loadQuestions(ids){if(!Array.isArray(ids)||!ids.length)throw new Error('問題IDがありません。');const papers=[...new Set(ids.map(x=>String(x).slice(0,String(x).lastIndexOf('-'))))];if(papers.some(id=>!catalog.exams.some(e=>e.id===id)))throw new Error('問題IDが不正です。');const all=await loadBank(papers);return ids.map(id=>{const q=all.find(q=>q.id===id);if(!q)throw new Error('問題IDが不正です。');return q;});}
async function openAttempt(a){if(a.status==='running'){const active=read(KEY,null);if(active?.startedAt&&!active.result&&active.attemptId!==a.attemptId)throw new Error('別の受験が進行中です。先にその受験を終了してください。');session=a.session;if(!session)throw new Error('この記録には再開データがありません。');archive=false;bank=await loadQuestions(session.questionIds);persist();screen('running');tick();}else{archive=true;bank=await loadQuestions(a.result.answers.map(x=>x.id));session={...a,questionIds:bank.map(q=>q.id),answers:{},flags:{},index:0,result:a.result};screen('done');}}
$('open-status').onclick=()=>{try{status.open($('student-code').value,$('student-name').value);}catch(e){$('entry-error').textContent=e.message;}};
$('status-back').onclick=()=>screen('entry');
function uuid(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const s=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;}
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{$('storage-notice').hidden=false;$('storage-notice').textContent='このブラウザに保存できません。画面を閉じず、終了時に結果JSONをダウンロードしてください。';return false;}}
function persist(){if(session&&!archive){save(KEY,session);try{store.record(session);}catch{$('storage-notice').hidden=false;$('storage-notice').textContent='記録を保存できません。画面を閉じずJSONを保存してください。';}}}
async function loadExam(id){if(downloaded.has(id))return downloaded.get(id);const r=await fetch(`data/${id}.json`);if(!r.ok)throw new Error('問題を読み込めませんでした。ネットワークを確認してください。');const data=await r.json();if(data.questions.length!==100)throw new Error('問題データが不完全です。先生に確認してください。');downloaded.set(id,data.questions);return data.questions;}
async function loadBank(ids){return (await Promise.all(ids.map(loadExam))).flat();}
function applyView(){const c=$('exam');c.style.setProperty('--cbt-bg',view.bg);c.style.setProperty('--cbt-ink',view.ink);body.style.zoom=view.zoom/100;c.dataset.dark=Number.parseInt(view.bg.slice(1,3),16)<120;$('bg').value=view.bg;$('ink').value=view.ink;$('zoom').value=view.zoom+'%';save(VIEW,view);}
function dialog(title,html,action,ok='確認する'){$('confirm-title').textContent=title;$('confirm-text').innerHTML=html;$('confirm-ok').textContent=ok;confirmAction=action;$('confirm').showModal();}
$('cancel').onclick=()=>{$('confirm').close();confirmAction=null;};$('confirm-ok').onclick=()=>{const action=confirmAction;confirmAction=null;$('confirm').close();action?.();};
function screen(next){phase=next;$('entry').hidden=next!=='entry';$('exam').hidden=['entry','status'].includes(next);$('status-screen').hidden=next!=='status';$('timer-box').hidden=!['running','list'].includes(next);$('phase-label').textContent=({guide:'操作説明',ready:'受験開始',running:'問題表示',list:'解答一覧',done:'試験結果'})[next]??'';if(session){$('who-code').textContent=session.studentCode;$('who-name').textContent=session.studentName;}render();window.scrollTo({top:0,behavior:'instant'});}
function choices(){return bank.filter(q=>session.questionIds.includes(q.id)).sort((a,b)=>session.questionIds.indexOf(a.id)-session.questionIds.indexOf(b.id));}
function button(label,id,cls='cbt-nav',disabled=false){return `<button type="button" id="${id}" class="${cls}" ${disabled?'disabled':''}>${label}</button>`;}
function image(q,lazy=false){return `<div class="q-image" style="aspect-ratio:${q.image.width}/${q.image.height}"><img src="${q.image.src}" style="top:-${q.image.y/q.image.height*100}%" alt="${esc(q.source)}の問題文・図表・選択肢" ${lazy?'loading="lazy"':''} onerror="this.closest('.q-image').outerHTML='<p class=error>問題画像を読み込めません。再読み込みまたは先生に確認してください。</p>'"></div>`;}
function foot(items){return `<nav class="cbt-foot" aria-label="問題移動">${items.join('')}</nav>`;}
$('references').onclick=()=>{const q=choices()[session.index],e=catalog.exams.find(e=>e.id===q.examId);dialog(`${e.label} 参考資料`,`<p>資料を開いている間も試験時間は進みます。</p><div class="reference-pages">${e.references.map((src,i)=>`<img src="${src}" alt="${esc(e.label)} 参考資料 ${i+1}ページ" loading="lazy">`).join('')}</div>`,null,'閉じる');};
const guides=[['画面と時間について','画面上部に現在時刻・受験番号・氏名・残り時間を表示します。時間が0になると自動で採点します。ページを閉じても残り時間は進みます。'],['画面の見え方を変える','白黒反転・背景色・文字色・表示倍率を変更できます。問題はIPAの原本画像です。文字や図表が小さいときは表示倍率を上げてください。'],['解答と見直し','原本の選択肢を読み、その下のア・イ・ウ・エを選びます。解答は変更できます。「後で見直す」を付けると、解答一覧に印が付きます。'],['提出と結果','解答一覧から提出します。未解答は不正解として採点します。終了後、分野別の正答率と正解を確認し、結果JSONをダウンロードして提出してください。']];
function render(){if(['entry','status'].includes(phase))return;const qs=choices(),answered=qs.filter(q=>Number.isInteger(session.answers[q.id])).length;
 if(phase==='guide'){body.innerHTML=`<div class="cbt-guide-head"><h2>${guides[guidePage][0]}</h2><span>${guidePage+1}/4ページ</span></div><div class="cbt-guide-body"><p>${guides[guidePage][1]}</p><p class="cbt-note">${esc(session.title)}／${qs.length}問／${session.minutes}分</p></div>${foot([button('最初へ','g-first','cbt-nav',guidePage===0),button('前へ','g-prev','cbt-nav',guidePage===0),button('次へ','g-next','cbt-nav',guidePage===3),button('試験開始画面へ','g-ready','cbt-go')])}`;$('g-first').onclick=()=>{guidePage=0;render();};$('g-prev').onclick=()=>{guidePage--;render();};$('g-next').onclick=()=>{guidePage++;render();};$('g-ready').onclick=()=>screen('ready');}
 if(phase==='ready'){body.innerHTML=`<h2>試験開始</h2><dl class="cbt-summary"><div><dt>試験</dt><dd>${esc(session.title)}</dd></div><div><dt>問題数</dt><dd>${qs.length}問</dd></div><div><dt>制限時間</dt><dd>${session.minutes}分</dd></div></dl><p class="cbt-note">「試験開始」を押した時点から時間が動き始めます。先生の合図を待ってください。</p>${foot([button('操作説明へ','ready-back'),button('試験開始','start','cbt-go')])}`;$('ready-back').onclick=()=>screen('guide');$('start').onclick=async()=>{if(session.startedAt)return;$('start').disabled=true;try{session=await store.start(session);persist();screen('running');tick();}catch(e){dialog('試験を開始できません',`<p>${esc(e.message)}</p>`,null,'閉じる');$('start').disabled=false;}};}
 if(phase==='running'){const q=qs[session.index];body.innerHTML=`<div class="cbt-qhead"><span class="cbt-qno" tabindex="-1" id="q-focus">問 ${session.index+1} / ${qs.length}</span><span class="cbt-qfield">${esc(q.domain)}</span><label class="cbt-flag ${session.flags[q.id]?'on':''}"><input id="flag" type="checkbox" ${session.flags[q.id]?'checked':''}>後で見直す</label></div><p class="source">${esc(q.source)}</p>${image(q)}<div class="cbt-choice-row" role="radiogroup" aria-label="解答の選択">${LABELS.map((l,i)=>`<button type="button" role="radio" aria-checked="${session.answers[q.id]===i}" class="cbt-choice ${session.answers[q.id]===i?'on':''}" data-choice="${i}"><span class="cbt-mark">${l}</span><span>${l}を選択</span></button>`).join('')}</div><div class="cbt-state">解答済み <b id="answered">${answered}</b> / ${qs.length}問 <span id="unanswered" class="cbt-unanswered" ${session.answers[q.id]!==undefined?'hidden':''}>この問題は未解答です</span></div>${foot([button('最初の問題へ','first','cbt-nav',session.index===0),button('前の問題へ','previous','cbt-nav',session.index===0),button('次の問題へ','next','cbt-nav',session.index===qs.length-1),button('解答一覧へ','list','cbt-go ghost')])}`;
 body.querySelectorAll('[data-choice]').forEach(b=>{b.onclick=()=>{if(expired())return;session.answers[q.id]=+b.dataset.choice;persist();body.querySelectorAll('[data-choice]').forEach(x=>{x.classList.toggle('on',x===b);x.setAttribute('aria-checked',String(x===b));});$('answered').textContent=qs.filter(x=>session.answers[x.id]!==undefined).length;$('unanswered').hidden=true;};b.onkeydown=e=>{if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();const next=(+b.dataset.choice+(['ArrowRight','ArrowDown'].includes(e.key)?1:3))%4;const x=body.querySelector(`[data-choice="${next}"]`);x.focus();x.click();}};});$('flag').onchange=e=>{if(expired())return;session.flags[q.id]=e.target.checked;persist();e.target.closest('label').classList.toggle('on',e.target.checked);};$('first').onclick=()=>go(0);$('previous').onclick=()=>go(session.index-1);$('next').onclick=()=>go(session.index+1);$('list').onclick=()=>{if(!expired())screen('list');};}
 if(phase==='list'){const flags=qs.filter(q=>session.flags[q.id]).length;body.innerHTML=`<h2>解答一覧</h2><div class="cbt-legend"><span class="cbt-legend-item done">解答済み</span><span class="cbt-legend-item todo">未解答</span><span class="cbt-legend-item mark">見直しの印</span></div><div class="cbt-grid">${qs.map((q,i)=>`<button class="cbt-cell ${session.answers[q.id]!==undefined?'done':'todo'} ${session.flags[q.id]?'mark':''}" data-go="${i}" aria-label="問${i+1} ${session.answers[q.id]!==undefined?'解答済み':'未解答'} ${session.flags[q.id]?'見直し':''}">${i+1}</button>`).join('')}</div><dl class="cbt-summary"><div><dt>解答済み</dt><dd>${answered} / ${qs.length}問</dd></div><div><dt>未解答</dt><dd>${qs.length-answered}問</dd></div><div><dt>見直しの印</dt><dd>${flags}問</dd></div></dl>${foot([button('問題にもどる','back-question'),button('解答を提出する','submit','cbt-go danger')])}`;body.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(+b.dataset.go));$('back-question').onclick=()=>go(session.index);$('submit').onclick=()=>{if(expired())return;dialog('提出しますか？',`<p class="dialog-line">未解答は${qs.length-answered}問、見直しの印は${flags}問です。提出後は解答を変更できません。</p>`,()=>finish(false),'提出して採点する');};}
 if(phase==='done')renderResult(qs);
}
function go(i){if(expired())return;session.index=i;persist();screen('running');$('q-focus').focus({preventScroll:true});}
function expired(){if(session?.startedAt&&!session?.result&&remainingSeconds(session.deadline)===0){finish(true);return true;}return false;}
function tick(){$('now').textContent=new Date().toLocaleTimeString('ja-JP',{hour12:false,timeZone:'Asia/Tokyo'});if(session?.startedAt&&!session.result){const s=remainingSeconds(session.deadline);$('timer').textContent=clock(s);$('timer-box').classList.toggle('warn',s<=Math.min(300,session.minutes*12));if(s===0)finish(true);}}
function finish(timeUp,abandoned=false){if(session.result)return;if($('confirm').open)$('confirm').close();const qs=choices(),end=timeUp?session.deadline:Math.min(Date.now(),session.deadline);session.result={schemaVersion:1,round:session.round,abandoned,app:'info1_IPass',attemptId:session.attemptId,examId:session.settings.examId,studentCode:session.studentCode,studentName:session.studentName,title:session.title,settings:session.settings,startedAt:session.startedAt,finishedAt:new Date(end).toISOString(),elapsedSeconds:Math.max(0,Math.floor((end-Date.parse(session.startedAt))/1000)),timeUp,...grade(qs,session.answers)};persist();let h=read(HISTORY,[]);h=h.filter(x=>x.attemptId!==session.attemptId);h.push(session.result);save(HISTORY,h.slice(-100));screen('done');}
function renderResult(qs){const r=session.result;const wrong=r.answers.filter(a=>!a.correct).length;body.innerHTML=`<h2>第${r.round??session.round??'—'}回の試験結果${r.abandoned?'（中断終了）':''}</h2>${r.timeUp?'<p class="notice">時間終了のため、自動で採点しました。</p>':''}<p>${esc(r.studentCode)}　${esc(r.studentName)} ／ ${esc(r.title)}</p><div class="result-top"><div class="score">得点率<strong>${r.score}<small> / 100</small></strong><p>正解 ${r.correct} / ${r.total}問</p><small>所要時間 ${clock(r.elapsedSeconds)}</small></div><div><h3>分野別の正答率</h3>${r.byDomain.map(d=>`<div class="domain-result"><span>${esc(d.domain)}</span><progress value="${d.rate??0}" max="100"></progress><strong>${d.rate===null?'対象外':d.rate+'%'}</strong></div>`).join('')}<p class="hint">各問を同じ配点で採点しています。本試験のIRT評価点・合否とは異なります。</p></div></div><section class="panel"><h3>学習アドバイス</h3><p>${esc(advice(r))}</p></section><div class="result-actions">${button('結果JSONをダウンロード','download','primary')}${button('ステータス・履歴保存・送信','result-status','primary')}${button('結果を印刷','print','secondary')}${button('新しいテストへ','another','secondary')}</div><p id="server-status" class="hint">このブラウザに保存しました。結果JSONをダウンロードして先生に提出してください。</p><section class="panel"><h3>解答の確認</h3><div class="result-actions">${button(`間違えた問題だけ（${wrong}問）`,'review-wrong','secondary')}${button(`全${r.total}問`,'review-all','secondary')}</div><div id="review">${qs.filter(q=>reviewFilter==='all'||!r.answers.find(a=>a.id===q.id).correct).map(q=>{const a=r.answers.find(a=>a.id===q.id);return `<details class="review-item"><summary><span class="${a.correct?'good':'bad'}">${a.correct?'正解':a.picked<0?'未解答':'不正解'}</span>　${esc(q.source)}　あなた：${a.picked<0?'未解答':LABELS[a.picked]} ／ 正解：${LABELS[q.answer]}</summary>${image(q,true)}<p><a href="${esc(q.explanationUrl)}" target="_blank" rel="noopener noreferrer">この問題の解説を外部サイトで確認する</a></p></details>`;}).join('')||'<p>全問正解です。</p>'}</div></section>`;$('download').onclick=()=>downloadJson(r);$('print').onclick=()=>window.print();$('result-status').onclick=()=>status.open(r.studentCode,r.studentName);$('another').onclick=()=>{dialog('新しいテストへ',`<p class="dialog-line">結果JSONを保存しましたか？この結果はブラウザの受験履歴にも残ります。</p>`,()=>{if(!archive)localStorage.removeItem(KEY);archive=false;session=null;$('resume-box').hidden=!read(KEY,null);screen('entry');},'表紙に戻る');};$('review-wrong').onclick=()=>{reviewFilter='wrong';renderResult(qs);};$('review-all').onclick=()=>{reviewFilter='all';renderResult(qs);};}
export function downloadJson(r){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.href=u;a.download=`IPass_${r.studentCode}_${r.attemptId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function modeChanged(){const m=$('mode').value;$('custom-fields').hidden=m!=='practice';$('domain-field').hidden=m!=='practice';$('ratio-note').hidden=m==='year';$('exam-year').querySelector('[value=all]').disabled=m==='year';if(m==='year'&&$('exam-year').value==='all')$('exam-year').value=catalog.exams[0].id;}
$('mode').onchange=modeChanged;$('invert').onclick=()=>{[view.bg,view.ink]=[view.ink,view.bg];applyView();};$('bg').oninput=e=>{view.bg=e.target.value;applyView();};$('ink').oninput=e=>{view.ink=e.target.value;applyView();};$('zoom').onchange=e=>{view.zoom=parseInt(e.target.value);applyView();};$('reset-view').onclick=()=>{view={bg:'#fffdf4',ink:'#17263c',zoom:100};applyView();};
$('entry-form').onsubmit=async e=>{e.preventDefault();if(busy)return;$('entry-error').textContent='';const code=$('student-code').value,name=normalizeName($('student-name').value);if(!validStudent(code,name)){$('entry-error').textContent='4桁番号と、姓と名の間にスペースを入れた氏名を入力してください。';return;}const active=read(KEY,null);if(active&&!active.result){$('entry-error').textContent='前の受験が残っています。「続きから受験する」か「前の受験を取り消す」を選んでください。';return;}
 busy=true;$('prepare').disabled=true;$('prepare').textContent='問題を準備中…';try{store.checkName(code,name);if(store.error)throw new Error(store.error);const records=store.forStudent(code);if(records.length>=5)throw new Error('5回のチャレンジを使い切りました。ステータスを確認してください。');if(records.some(a=>a.status==='running'))throw new Error('受験中の記録があります。ステータスから再開してください。');const mode=$('mode').value,year=$('exam-year').value,ids=year==='all'?catalog.exams.map(x=>x.id):[year];bank=await loadBank(ids);const domain=mode==='practice'?$('domain').value:'all',count=mode==='year'?100:mode==='school'?35:+$('question-count').value,minutes=mode==='year'?120:mode==='school'?40:+$('minutes').value;if(!Number.isInteger(minutes)||minutes<1||minutes>180)throw new Error('制限時間は1〜180分で入力してください。');const qs=selectQuestions(bank,{mode,domain,count});const settings={mode,examId:year,domain,count:qs.length,minutes};const title=(year==='all'?'全15回':catalog.exams.find(x=>x.id===year).label)+' ／ '+(domain==='all'?'全分野':domain);dialog('受験者情報の確認',`<p class="dialog-line"><b>${esc(code)}　${esc(name)}</b></p><p class="dialog-line">${esc(title)}<br>${qs.length}問 ／ ${minutes}分<br>第${records.length+1}回 / 5回（試験開始で1回使用）<br>${DOMAINS.map(d=>esc(d)+' '+qs.filter(q=>q.domain===d).length+'問').join('・')}</p>`,()=>{archive=false;session={attemptId:uuid(),studentCode:code,studentName:name,title,settings,minutes,questionIds:qs.map(x=>x.id),answers:{},flags:{},index:0,startedAt:null,deadline:null,result:null};persist();guidePage=0;screen('guide');},'操作説明へ進む');}catch(err){$('entry-error').textContent=err.message;}finally{busy=false;$('prepare').disabled=false;$('prepare').textContent='受験者情報を確認する';}};
async function resume(){const s=read(KEY,null);if(!s)return;$('resume').disabled=true;try{const ids=[...new Set(s.questionIds.map(x=>x.slice(0,x.lastIndexOf('-'))))];bank=await loadBank(ids);if(s.questionIds.some(id=>!bank.some(q=>q.id===id)))throw new Error('問題データが更新されています。先生に確認してください。');session=s;archive=false;if(s.result){screen('done');}else if(s.startedAt){screen('running');tick();}else screen('ready');}catch(err){$('entry-error').textContent=err.message;}finally{$('resume').disabled=false;}}
$('resume').onclick=resume;$('discard').onclick=()=>dialog('前の受験を中断終了しますか？','<p class="dialog-line">開始済みの場合は中断終了として記録を残し、1回分を使用します。開始前の場合は回数を使いません。</p>',async()=>{try{const old=read(KEY,null);if(old?.startedAt&&!old.result){archive=false;bank=await loadQuestions(old.questionIds);session=old;finish(false,true);}else{localStorage.removeItem(KEY);session=null;screen('entry');}$('resume-box').hidden=true;}catch(e){$('entry-error').textContent=e.message;}},'中断終了する');
window.addEventListener('beforeunload',e=>{if(session?.startedAt&&!session.result){e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',tick);setInterval(tick,1000);
try{const r=await fetch('data/catalog.json');if(!r.ok)throw new Error();catalog=await r.json();if(catalog.exams.length!==15)throw new Error();$('bank-count').textContent=`${catalog.exams.length}回分・${catalog.totalQuestions.toLocaleString()}問`;$('exam-year').insertAdjacentHTML('beforeend',catalog.exams.map(x=>`<option value="${x.id}">${esc(x.label)}（${x.questionCount}問）</option>`).join(''));$('prepare').disabled=false;const p=new URLSearchParams(location.search);for(const [param,id] of [['mode','mode'],['year','exam-year'],['domain','domain'],['count','question-count']])if([...$(id).options].some(x=>x.value===p.get(param)))$(id).value=p.get(param);if(p.has('minutes'))$('minutes').value=p.get('minutes');modeChanged();const old=read(KEY,null);if(old){$('resume-box').hidden=false;$('resume-label').textContent=`${old.studentCode} ${old.studentName} ／ ${old.result?'前回の結果を表示できます':'前回の続きがあります'}`;if(old.result)$('resume').textContent='前回の結果を表示する';}view={...view,...read(VIEW,{})};applyView();}catch{$('entry-error').textContent='問題データを読み込めませんでした。ページを再読み込みしてください。';}
