import {toCsv} from './core.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let index,rows=[];
const jsonButton=$('aspect-json');
jsonButton.onclick=async()=>{jsonButton.disabled=true;try{const papers=await Promise.all(index.papers.map(async p=>{const r=await fetch(p.path);if(!r.ok)throw new Error(p.label+'の分類データを読み込めません。');return r.json();}));const questions=Object.assign({},...papers.map(p=>p.questions));if(Object.keys(questions).length!==1500)throw new Error('全1,500問の取得を確認できません。');const value={app:'info1_IPass',kind:'question-aspect-classification',exportedAt:new Date().toISOString(),...index,questions},u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='IPass_question_aspects.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('aspect-export-message').textContent='全1,500問の一次分類・理由・OCR・出典をJSONに出力しました。';}catch(e){$('aspect-export-message').textContent=e.message;}finally{jsonButton.disabled=false;}};
async function render(){try{const id=$('aspect-year').value,paper=index.papers.find(x=>x.id===id),[meta,bank]=await Promise.all([fetch(paper.path).then(r=>r.json()),fetch('data/'+id+'.json').then(r=>r.json())]);const map=new Map(bank.questions.map(q=>[q.id,q]));rows=Object.entries(meta.questions).filter(([id,a])=>(!$('aspect-filter').value||a.aspect===$('aspect-filter').value)&&(!$('aspect-flag').checked||a.needsVisualReview));$('aspect-count').textContent=`全体の一次分類：知識・技能 ${index.counts['知識・技能']}問 ／ 思考・判断・表現 ${index.counts['思考・判断・表現']}問。表示 ${rows.length}問。`;$('aspect-items').innerHTML=rows.map(([id,a])=>{const q=map.get(id),im=q.image;return `<details class="review-item"><summary>${esc(id)} ／ ${esc(a.aspect)}${a.needsVisualReview?' ／ OCR要確認候補':''}</summary><p>${esc(a.reason)}</p><p class="hint">検出根拠：${esc(a.evidence)}</p><pre style="white-space:pre-wrap">${esc(a.stem)}</pre><div class="q-image" style="aspect-ratio:${im.width}/${im.height}"><img loading="lazy" src="${esc(im.src)}" style="top:-${im.y/im.height*100}%" alt="${esc(q.source)}の原本"></div><p>${esc(q.source)}</p></details>`;}).join('');}catch(e){$('aspect-count').textContent='分類データを読み込めません。 '+e.message;}}
for(const id of ['aspect-year','aspect-filter','aspect-flag'])$(id).onchange=render;
$('aspect-csv').onclick=()=>{const u=URL.createObjectURL(new Blob([toCsv([['問題ID','観点','分野','分類理由','検出根拠','OCR要確認','出典'],...rows.map(([id,a])=>[id,a.aspect,a.domain,a.reason,a.evidence,a.needsVisualReview?'はい':'いいえ',a.source])])],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='IPass_aspect_classification.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
try{index=await fetch('data/question-aspects.json').then(r=>r.json());$('aspect-year').innerHTML=index.papers.map(e=>`<option value="${esc(e.id)}">${esc(e.label)}</option>`).join('');await render();jsonButton.disabled=false;}catch(e){$('aspect-count').textContent=e.message;}
