import {teacherStore} from './teacher-store.js';
import {studentComparison} from './teacher-model.js';
import {comparisonKey,comparisonLabel} from './progress.js';
import {DOMAINS} from './core.js';
import {drawProgressChart,chartLegend} from './progress-chart.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=[],people=[],selected=[],visibility=()=>new Set(['総合',...DOMAINS]);
const percent=v=>v==null?'—':v+'%',delta=v=>v==null?'比較待ち':(v>0?'+':'')+v+'ポイント';
function render(keepGroup=false){const p=people.find(p=>p.code===$('compare-student').value);if(!p)return;const all=studentComparison(records,p.code,p.name),groups=[...new Map(all.complete.map(r=>[comparisonKey(r),comparisonLabel(r)])).entries()],key=keepGroup?$('compare-group').value:all.key;$('compare-group').innerHTML=groups.map(([k,l])=>`<option value="${esc(k)}">${esc(l)}</option>`).join('');if(groups.some(([k])=>k===key))$('compare-group').value=key;const c=studentComparison(records,p.code,p.name,$('compare-group').value);selected=c.selected.map(r=>({round:r.round,result:r}));$('compare-message').textContent=c.challenge.length?'':'本チャレンジの提出がありません。';$('compare-summary').innerHTML=[['初回',percent(c.first?.score)],['最新',percent(c.latest?.score)],['最高',percent(c.best)],['伸び',delta(c.gain)]].map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong></div>`).join('');visibility=chartLegend($('compare-legend'),v=>drawProgressChart($('compare-chart'),selected,v));drawProgressChart($('compare-chart'),selected,visibility());$('compare-domains').innerHTML='<table><thead><tr><th>分野</th><th>初回</th><th>最新</th><th>伸び</th></tr></thead><tbody>'+DOMAINS.map(d=>{const first=c.first?.byDomain.find(x=>x.domain===d)?.rate,last=c.latest?.byDomain.find(x=>x.domain===d)?.rate;return `<tr><td>${d}</td><td>${percent(first)}</td><td>${percent(last)}</td><td>${delta(c.selected.length>1&&first!=null&&last!=null?last-first:null)}</td></tr>`;}).join('')+'</tbody></table>';$('compare-records').innerHTML=c.challenge.map(r=>`<tr><td>第${r.round}回</td><td>${r.abandoned?'中断終了':'終了'}</td><td>${r.score}% (${r.correct}/${r.total})</td>${DOMAINS.map(d=>`<td>${percent(r.byDomain.find(x=>x.domain===d)?.rate)}</td>`).join('')}<td>${esc(new Date(r.finishedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}))}</td></tr>`).join('')||'<tr><td colspan="7">提出記録なし</td></tr>';$('compare-practice').textContent=`練習提出 ${c.practice.length}件 ／ 本チャレンジ中断終了 ${c.abandoned}件。`;
}
new ResizeObserver(()=>drawProgressChart($('compare-chart'),selected,visibility())).observe($('compare-chart'));$('compare-student').onchange=()=>render();$('compare-group').onchange=()=>render(true);
try{records=await teacherStore.records();people=await teacherStore.roster();if(!people.length)people=[...new Map(records.map(r=>[r.studentCode,{code:r.studentCode,name:r.studentName}])).values()];people.sort((a,b)=>a.code.localeCompare(b.code));$('compare-student').innerHTML=people.map(p=>`<option value="${esc(p.code)}">${esc(p.code)} ${esc(p.name)}</option>`).join('');const code=new URLSearchParams(location.search).get('code');if(people.some(p=>p.code===code))$('compare-student').value=code;if(!people.length)$('compare-message').textContent='管理画面で名簿・提出データを読み込んでください。';else render();}catch(e){$('compare-message').textContent=e.message;}
