import {DOMAINS,normalizeName} from './core.js';
import {isChallenge,isCancelled,comparisonKey,comparisonLabel} from './progress.js';
import {uniqueResults,questionSummary} from './analytics-model.js';
import {ASPECTS,aspectScores,practiceEvidence} from './assessment.js';
const rounded=n=>Math.round(n*10)/10;
export function descriptive(values){const a=values.filter(Number.isFinite).sort((x,y)=>x-y),n=a.length;if(!n)return {n:0,mean:null,median:null,sd:null,min:null,max:null};const mean=a.reduce((s,x)=>s+x,0)/n;return {n,mean:rounded(mean),median:rounded(n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2),sd:rounded(Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/n)),min:a[0],max:a.at(-1)};}
export function challengeGroups(records){return [...new Map(uniqueResults(records).filter(r=>isChallenge(r)&&!r.abandoned&&!isCancelled(r)).sort((a,b)=>Date.parse(a.finishedAt)-Date.parse(b.finishedAt)).map(r=>[comparisonKey(r),comparisonLabel(r)])).entries()].map(([key,label])=>({key,label}));}
function dateLimits(from,to){const parse=d=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(d))throw new Error('集計期間の日付を確認してください。');const n=Date.parse(d+'T00:00:00+09:00');if(!Number.isFinite(n)||new Date(n+9*3600000).toISOString().slice(0,10)!==d)throw new Error('集計期間の日付を確認してください。');return n;};const start=from?parse(from):-Infinity,end=to?parse(to)+86400000:Infinity;if(start>=end)throw new Error('終了日は開始日以降にしてください。');return {start,end};}
const eligibleAspect=r=>{const a=aspectScores(r.answers??[]);return r.total===75&&a[0].total===30&&a[1].total===45;};
function paired(rows){const pairs=rows.filter(x=>x.length>1);return {n:pairs.length,first:descriptive(pairs.map(x=>x[0].score)),last:descriptive(pairs.map(x=>x.at(-1).score)),gain:descriptive(pairs.map(x=>x.at(-1).score-x[0].score)),improved:pairs.filter(x=>x.at(-1).score>x[0].score).length,unchanged:pairs.filter(x=>x.at(-1).score===x[0].score).length,decreased:pairs.filter(x=>x.at(-1).score<x[0].score).length};}
function summarizePeople(people,completed,allRecords,metadata){
 const rows=people.map(p=>completed.filter(r=>r.studentCode===p.code).sort((a,b)=>Date.parse(a.finishedAt)-Date.parse(b.finishedAt)||a.round-b.round)),latest=rows.flatMap(x=>x.length?[x.at(-1)]:[]),full=rows.filter(x=>[1,2,3,4,5].every(n=>x.some(r=>r.round===n))&&x.every(eligibleAspect));
 const final=full.map(x=>x.reduce((s,r)=>s+r.correct,0)/375*100);
 const practice=people.map(p=>practiceEvidence(allRecords.filter(r=>r.studentCode===p.code).map(r=>({...r,status:r.abandoned?'abandoned':'completed',result:r})),metadata)).filter(e=>e.completed>0);
 const aspects=ASPECTS.map(aspect=>({aspect,...descriptive(latest.map(r=>{const a=aspectScores(r.answers??[]).find(x=>x.aspect===aspect);return a.total?a.correct/a.total*100:null;}))}));
 const domain=DOMAINS.map(d=>({domain:d,...descriptive(latest.map(r=>r.byDomain?.find(x=>x.domain===d)?.rate))}));
 const round15=rows.flatMap(x=>{const a=x.find(r=>r.round===1),b=x.find(r=>r.round===5);return a&&b?[[a,b]]:[];});
 return {enrolled:people.length,completedStudents:latest.length,completedAttempts:completed.length,completed5:rows.filter(x=>[1,2,3,4,5].every(n=>x.some(r=>r.round===n))).length,latest:descriptive(latest.map(r=>r.score)),final5:descriptive(final),paired:paired(rows),round1to5:paired(round15),byDomain:domain,byAspect:aspects,rounds:[1,2,3,4,5].map(round=>({round,...descriptive(completed.filter(r=>r.round===round).map(r=>r.score))})),distribution:[0,20,40,60,80].map(start=>({label:start===80?'80〜100':start+'〜'+(start+19),min:start,max:start===80?100:start+19,count:latest.filter(r=>r.score>=start&&(start===80?r.score<=100:r.score<start+20)).length})),practice:{participants:practice.length,completed:practice.reduce((s,e)=>s+e.completed,0),attempts:descriptive(practice.map(e=>e.completed)),retryProblems:practice.reduce((s,e)=>s+e.retryUnique,0),improvedProblems:practice.reduce((s,e)=>s+e.improvedUnique,0),improvementStudents:practice.filter(e=>e.retryUnique>0).length,transferCorrect:practice.reduce((s,e)=>s+e.transferCorrect,0),transferTotal:practice.reduce((s,e)=>s+e.transferTotal,0)}};
}
export function buildStatistics(roster,records,metadata={questions:{}},{group,classCode='',from='',to='',label=''}={}){
 const unique=uniqueResults(records),known=new Map(roster.map(p=>[p.code,normalizeName(p.name)])),matched=unique.filter(r=>!roster.length||known.get(r.studentCode)===normalizeName(r.studentName)),limits=dateLimits(from,to),inPeriod=r=>{const t=Date.parse(r.finishedAt);return Number.isFinite(t)&&t>=limits.start&&t<limits.end;},period=matched.filter(r=>(!classCode||r.studentCode.startsWith(classCode))&&inPeriod(r)),groups=challengeGroups(matched),selectedGroup=group===undefined?groups.at(-1)?.key:group;
 // Keep one result per student/round in the selected condition. Cancelled records have already been excluded.
 const candidates=period.filter(r=>isChallenge(r)&&!r.abandoned&&!isCancelled(r)&&comparisonKey(r)===selectedGroup&&Number.isInteger(r.round)&&r.round>=1&&r.round<=5),dedup=new Map();for(const r of candidates){const key=r.studentCode+':'+r.round,old=dedup.get(key);if(!old||Date.parse(r.finishedAt)>Date.parse(old.finishedAt))dedup.set(key,r);}const completed=[...dedup.values()];
 const people=(roster.length?roster:[...new Map(period.map(r=>[r.studentCode,{code:r.studentCode}])).values()]).filter(p=>!classCode||p.code.startsWith(classCode)),overall=summarizePeople(people,completed,period,metadata),classes=[...new Set(people.map(p=>p.code.slice(0,2)))].sort().map(c=>({classCode:c,...summarizePeople(people.filter(p=>p.code.startsWith(c)),completed.filter(r=>r.studentCode.startsWith(c)),period.filter(r=>r.studentCode.startsWith(c)),metadata)})),topics=new Map();
 for(const r of completed)for(const a of r.answers??[]){const m=metadata.questions?.[a.id],key=m?.topicId??a.domain??'unclassified';let t=topics.get(key);if(!t){t={topicId:key,topic:m?.topic??a.domain??'未分類',total:0,correct:0,unanswered:0,students:new Set()};topics.set(key,t);}t.total++;t.correct+=a.correct?1:0;t.unanswered+=a.picked<0?1:0;t.students.add(r.studentCode);}
 return {app:'info1_IPass',kind:'anonymous-teaching-statistics',schemaVersion:1,generatedAt:new Date().toISOString(),conditions:{label,classCode,from,to,timeZone:'Asia/Tokyo',group:selectedGroup??null,groupLabel:groups.find(x=>x.key===selectedGroup)?.label??'対象条件なし',rosterLoaded:roster.length>0,classificationStatus:'provisional-content-v1'},quality:{inputRecords:unique.length,unmatchedRecords:unique.length-matched.length,periodRecords:period.length,cancelled:period.filter(isCancelled).length,abandoned:period.filter(r=>r.abandoned&&!isCancelled(r)).length,duplicateRounds:candidates.length-completed.length,aspectUnclassifiedLatest:overall.completedStudents-Math.min(...overall.byAspect.map(a=>a.n))},overall,classes,topics:[...topics.values()].map(t=>({...t,students:t.students.size,rate:rounded(t.correct/t.total*100)})).sort((a,b)=>a.rate-b.rate||b.total-a.total),questions:questionSummary(completed,{mode:'school',group:selectedGroup??'no-group'}),notes:['氏名・受験番号・受験IDを含まない集計出力。集計期間は終了日時で判定。','名簿と番号・氏名が一致する提出記録が対象。未提出者の得点は0点にしない。名簿未読込の場合、名簿人数・提出率は算出しない。','本チャレンジは同じ出題条件で中断・取消しを除外。各生徒・各実施回1件。最新得点分布は1人1件。','各回平均の参加者は異なり得る。伸びは同一生徒の比較可能な記録を用いる。抽選問題・年度の難易度は異なる。','5回総合は全5回で各回30問／45問の条件を満たした生徒だけ。観点分類は一次分類で教員確認未完了。','分野・観点の平均は生徒別正答率の平均。問題・参考単元の母数は解答件数（未解答を含む）。','練習は主体性を検討する参考記録であり、態度の評定や学習効果の因果関係を自動判定しない。','標準偏差は対象者集団内の記述統計（母標準偏差）。少人数の割合・問題正答率は変動しやすい。']};
}
export function statisticsCsv(report){const statLabels={mean:'平均',median:'中央値',sd:'標準偏差',min:'最小',max:'最大'},practiceLabels={participants:'練習提出者',completed:'練習終了回数',retryProblems:'誤答への再挑戦問題数',improvedProblems:'誤答からの改善問題数',improvementStudents:'誤答へ再挑戦した人数',transferCorrect:'苦手単元の別問題の正解数',transferTotal:'苦手単元の別問題の解答数'};const rows=[['区分','項目','クラス','人数・件数','値','単位'],['条件','集計名','', '',report.conditions.label,''],['条件','出題条件','','',report.conditions.groupLabel,''],['条件','期間','','',report.conditions.from+'〜'+report.conditions.to,'終了日・日本時間']];
 const append=(scope,key,c,s)=>{for(const p of ['mean','median','sd','min','max'])rows.push([scope,key+' '+statLabels[p],c,s.n,s[p]??'',p==='sd'||key.includes('差')?'ポイント':'%']);};append('全体','最新得点','',report.overall.latest);append('全体','5回総合','',report.overall.final5);append('全体','初回→最新の差','',report.overall.paired.gain);append('全体','第1→第5回の差','',report.overall.round1to5.gain);
 for(const c of report.classes){rows.push(['クラス','名簿人数',c.classCode,'',report.conditions.rosterLoaded?c.enrolled:'','人'],['クラス','完了提出者',c.classCode,'',c.completedStudents,'人'],['クラス','5回完了',c.classCode,'',c.completed5,'人']);append('クラス','最新得点',c.classCode,c.latest);append('クラス','初回→最新の差',c.classCode,c.paired.gain);append('クラス','第1→第5回の差',c.classCode,c.round1to5.gain);for(const d of c.byDomain)append('クラス分野',d.domain,c.classCode,d);for(const a of c.byAspect)append('クラス観点',a.aspect,c.classCode,a);}
 for(const r of report.overall.rounds)append('各回','第'+r.round+'回','',r);for(const d of report.overall.byDomain)append('分野',d.domain,'',d);for(const a of report.overall.byAspect)append('観点',a.aspect,'',a);for(const b of report.overall.distribution)rows.push(['得点分布',b.label,'',b.count,'','人']);for(const [stat,value] of Object.entries(report.overall.practice.attempts))if(stat!=='n')rows.push(['練習','終了回数 '+statLabels[stat],'',report.overall.practice.attempts.n,value??'','回']);for(const [key,value] of Object.entries(report.overall.practice))if(typeof value==='number')rows.push(['練習',practiceLabels[key]??key,'','',value,key.includes('Students')||key==='participants'?'人':key==='completed'?'回':'問']);
 for(const t of report.topics)rows.push(['参考単元',t.topic,'',t.total,t.rate,'%（人数 '+t.students+'、正解 '+t.correct+'、未解答 '+t.unanswered+'）']);for(const q of report.questions)rows.push(['問題',q.id+' '+q.source,'',q.total,q.rate,'%（人数 '+q.students+'、正解 '+q.correct+'、未解答 '+q.unanswered+'）']);for(const note of report.notes)rows.push(['注記',note,'','','','']);return rows;
}
