import {DOMAINS,normalizeName,validStudent,toCsv,grade} from './core.js';
import {MAX_ATTEMPTS,STATUS_LABELS,comparisonKey,comparisonLabel,summarize,mergeAttempts,isUuid,isChallenge,attemptKind,roundLabel} from './progress.js';
import {drawProgressChart,chartLegend} from './progress-chart.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function download(value,name,type='application/json'){const u=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export function createStatus(store,{screen,openAttempt,loadQuestions}){
 let profile=null,group=null,selected=[],visible=()=>new Set(['総合',...DOMAINS]);
 const message=s=>$('status-message').textContent=s;
 function render(){if(!profile)return;const records=store.forStudent(profile.code),challenges=records.filter(isChallenge),summary=summarize(challenges,group);group=summary.key;selected=summary.selected;
  $('status-who').textContent=profile.code+'　'+profile.name;$('status-storage').textContent='解答・受験回数・成績は、この端末のブラウザに保存します。学校サーバは提出先だけです。';$('status-count').textContent=`本チャレンジ ${challenges.length} / ${MAX_ATTEMPTS}回使用 ・ 残り${Math.max(0,MAX_ATTEMPTS-challenges.length)}回 ／ 練習 ${records.length-challenges.length}回（無制限）`;
  $('attempt-slots').innerHTML=[1,2,3,4,5].map(n=>{const r=challenges.find(a=>a.round===n);return `<div class="attempt-slot ${r?.status??'available'}"><b>第${n}回</b><span>${r?STATUS_LABELS[r.status]:'未実施'}</span><strong>${r?.result?r.result.score+'%':'—'}</strong></div>`;}).join('');
  const groups=new Map(challenges.filter(r=>r.status==='completed').map(r=>[comparisonKey(r),comparisonLabel(r)]));$('comparison-group').innerHTML=groups.size?[...groups].map(([k,l])=>`<option value="${esc(k)}" ${k===group?'selected':''}>${esc(l)}</option>`).join(''):'<option>終了した記録がありません</option>';$('comparison-group').disabled=!groups.size;
  const receipts=store.receipts(profile.code),sent=new Set(receipts.flatMap(r=>r.attemptIds)),pending=challenges.filter(a=>a.result&&!sent.has(a.attemptId));$('submission-receipt').textContent=receipts.length?`最終提出 ${new Date(receipts.at(-1).receivedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} ／ 受付番号 ${receipts.at(-1).receiptId} ／ 未提出の本チャレンジ終了記録 ${pending.length}回`:'このブラウザには提出完了の記録がありません。';const delta=v=>v==null?'—':(v>0?'+':'')+v+'ポイント';
  $('progress-summary').innerHTML=`<div class="metric"><span>最新の総合正答率</span><strong>${summary.latest==null?'—':summary.latest+'%'}</strong><small>${summary.firstRound?`第${summary.firstRound}回 → 第${summary.lastRound}回`:'受験終了後に表示'}</small><b>伸び ${summary.selected.length>1?delta(summary.gain):'比較待ち'}</b></div>`+summary.byDomain.map(d=>`<div class="metric"><span>${esc(d.domain)}</span><strong>${d.latest==null?'対象外':d.latest+'%'}</strong><small>正解 ${d.correct} / ${d.total}問</small><b>伸び ${summary.selected.length>1?delta(d.gain):'比較待ち'}</b></div>`).join('');
  visible=chartLegend($('progress-legend'),v=>drawProgressChart($('progress-chart'),selected,v));drawProgressChart($('progress-chart'),selected,visible());
  $('attempt-records').innerHTML=records.map(r=>`<tr><td>${esc(roundLabel(r))}</td><td>${esc(STATUS_LABELS[r.status])}<br><small>${esc(new Date(r.startedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}))}</small></td><td>${esc(comparisonLabel(r))}<br><small>${esc(r.title)}</small></td><td>${r.result?`${r.result.score}% (${r.result.correct}/${r.result.total})`:'—'}</td>${DOMAINS.map(d=>{const b=r.result?.byDomain.find(x=>x.domain===d);return `<td>${b?.rate!=null?b.rate+'% ('+b.correct+'/'+b.total+')':'—'}</td>`;}).join('')}<td><button class="secondary" data-attempt="${r.attemptId}">${r.status==='running'?'再開':'結果'}</button></td></tr>`).join('')||'<tr><td colspan="8">受験記録はまだありません。</td></tr>';
  document.querySelectorAll('[data-attempt]').forEach(b=>b.onclick=async()=>{try{await openAttempt(records.find(r=>r.attemptId===b.dataset.attempt));}catch(e){message(e.message);}});
 }
 $('comparison-group').onchange=e=>{group=e.target.value;render();};new ResizeObserver(()=>{if(profile&&!$('status-screen').hidden)drawProgressChart($('progress-chart'),selected,visible());}).observe($('progress-chart'));
 $('status-json').onclick=()=>download(store.packet(profile.code,profile.name),`IPass_${profile.code}_history.json`);
 $('status-csv').onclick=()=>{const rows=[['受験番号','氏名','実施回','状態','出題条件','総合正答率',...DOMAINS,'開始日時','終了日時'],...store.forStudent(profile.code).map(r=>[profile.code,profile.name,roundLabel(r),STATUS_LABELS[r.status],comparisonLabel(r),r.result?.score??'',...DOMAINS.map(d=>r.result?.byDomain.find(x=>x.domain===d)?.rate??''),r.startedAt,r.finishedAt??''])];download(toCsv(rows),`IPass_${profile.code}_progress.csv`,'text/csv;charset=utf-8');};
 $('status-send').onclick=async()=>{const ip=$('submit-ip').value.trim();if(!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(ip)||ip.split('.').some(x=>+x>255)){message('先生から指定されたIPv4アドレスを入力してください。例：192.168.1.50');return;}if(!store.forStudent(profile.code).length){message('提出する受験記録がありません。');return;}const packet=store.packet(profile.code,profile.name);$('status-send').disabled=true;message('送信中…');try{const res=await fetch(`http://${ip}:3000/api/submissions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(packet),credentials:'omit',redirect:'error',signal:AbortSignal.timeout(15000)}),r=await res.json();if(!res.ok||r.ok!==true||r.studentCode!==profile.code||typeof r.receiptId!=='string')throw new Error(r.error||'受付完了を確認できません。');try{localStorage.setItem('ipass:submit-ip',ip);store.saveReceipt(profile.code,r,packet.attempts);render();}catch{}message(`提出完了：受付番号 ${r.receiptId}。ブラウザの記録も残しています。`);}catch(e){message(`提出完了を確認できません。IPアドレス・サーバ起動・校内ネットワーク／ローカルネットワークのアクセス許可を確認してください。履歴JSONを保存して提出することもできます。${e.name==='TypeError'?'':' '+e.message}`);}finally{$('status-send').disabled=false;}};
 $('status-import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw new Error('ファイルが大きすぎます。');const p=JSON.parse(await file.text());if(p.app!=='info1_IPass'||p.kind!=='progress'||p.schemaVersion!==2||p.studentCode!==profile.code||normalizeName(p.studentName)!==profile.name||!Array.isArray(p.attempts)||p.attempts.length>10000)throw new Error('同じ番号・氏名の履歴JSONを選んでください。');const old=store.forStudent(profile.code),ids=new Set(),rounds=new Set(),validated=[];
  for(const a of p.attempts){if(!isUuid(a.attemptId)||ids.has(a.attemptId)||rounds.has(attemptKind(a)+':'+a.round)||!Number.isInteger(a.round)||a.round<1||a.studentCode!==profile.code||normalizeName(a.studentName)!==profile.name||!Number.isFinite(Date.parse(a.startedAt))||!['running','completed','abandoned'].includes(a.status))throw new Error('受験記録の形式が不正です。');ids.add(a.attemptId);rounds.add(attemptKind(a)+':'+a.round);
   const terminal=old.find(x=>x.attemptId===a.attemptId&&x.status!=='running');if(terminal){validated.push(terminal);continue;}
   const s=a.session,r=a.result,questions=r?await loadQuestions(r.answers?.map(x=>x.id)):await loadQuestions(s?.questionIds),picked={};if(!questions.length||questions.length>1500||new Set(questions.map(q=>q.id)).size!==questions.length)throw new Error('問題IDが不正です。');
   if(r){if(r.attemptId!==a.attemptId||r.studentCode!==profile.code||normalizeName(r.studentName)!==profile.name||!Array.isArray(r.answers)||!Number.isFinite(Date.parse(r.finishedAt))||a.status==='running')throw new Error('結果形式が不正です。');for(const x of r.answers){if(!Number.isInteger(x.picked)||x.picked< -1||x.picked>3)throw new Error('解答が不正です。');if(x.picked>=0)picked[x.id]=x.picked;}a.result={...r,round:a.round,abandoned:a.status==='abandoned',...grade(questions,picked)};delete a.session;}
   else{if(a.status!=='running'||s.attemptId!==a.attemptId||s.studentCode!==profile.code||normalizeName(s.studentName)!==profile.name||s.result||!Number.isFinite(s.deadline)||!Number.isInteger(s.index)||s.index<0||s.index>=questions.length||!s.answers||!s.flags||s.startedAt!==a.startedAt)throw new Error('再開データが不正です。');for(const [id,v] of Object.entries(s.answers))if(!questions.some(q=>q.id===id)||!Number.isInteger(v)||v<0||v>3)throw new Error('再開の解答が不正です。');s.round=a.round;}
   if(old.some(x=>attemptKind(x)===attemptKind(a)&&x.round===a.round&&x.attemptId!==a.attemptId))throw new Error('同じ実施回に異なる記録があります。元の履歴と確認してください。');validated.push(a);
  }
  const merged=mergeAttempts(old,validated);if(merged.filter(isChallenge).length>Math.max(MAX_ATTEMPTS,old.filter(isChallenge).length)||merged.filter(a=>a.status==='running').length>1)throw new Error('5回を超える記録、または複数の受験中の記録があります。');store.write(mergeAttempts(store.all(),validated));render();message('履歴を読み込みました。回数を引き継ぎ、公式解答で再採点しました。');
 }catch(err){message(err.message);}finally{e.target.value='';}};
 return {open(code,name){name=normalizeName(name);if(!validStudent(code,name))throw new Error('4桁番号と「姓 名」を入力してください。');store.checkName(code,name);profile={code,name};$('student-code').value=code;$('student-name').value=name;group=null;message('');try{$('submit-ip').value=localStorage.getItem('ipass:submit-ip')||'';}catch{}screen('status');render();},render};
}
