import {challengeAssessment,practiceEvidence,assessmentExport,ASPECTS} from './assessment.js';
import {DOMAINS,normalizeName,validStudent,toCsv,grade} from './core.js';
import {MAX_ATTEMPTS,STATUS_LABELS,comparisonKey,comparisonLabel,summarize,mergeAttempts,isUuid,isChallenge,isCancelled,attemptKind,roundLabel} from './progress.js';
import {drawProgressChart,chartLegend} from './progress-chart.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function download(value,name,type='application/json'){const u=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export function createStatus(store,{screen,openAttempt,loadQuestions,onCorrection,getMetadata}){
 let profile=null,group=null,selected=[],visible=()=>new Set(['総合',...DOMAINS]);
 const message=s=>$('status-message').textContent=s;
 const exportPacket=()=>({...store.packet(profile.code,profile.name),assessment:assessmentExport(store.forStudent(profile.code),getMetadata?.()??{questions:{}})});
 function render(){if(!profile)return;const records=store.forStudent(profile.code),challenges=records.filter(a=>isChallenge(a)&&!isCancelled(a)),summary=summarize(challenges,group);group=summary.key;selected=summary.selected;
  $('status-who').textContent=profile.code+'　'+profile.name;$('status-storage').textContent='解答・受験回数・成績は、この端末のブラウザに保存します。学校サーバは提出先だけです。';$('status-count').textContent=`本チャレンジ ${challenges.length} / ${MAX_ATTEMPTS}回使用 ・ 残り${Math.max(0,MAX_ATTEMPTS-challenges.length)}回 ／ 練習 ${records.filter(a=>!isChallenge(a)).length}回（無制限） ／ 取消し ${records.filter(isCancelled).length}回`;
  $('attempt-slots').innerHTML=[1,2,3,4,5].map(n=>{const r=challenges.find(a=>a.round===n);return `<div class="attempt-slot ${r?.status??'available'}"><b>第${n}回</b><span>${r?STATUS_LABELS[r.status]:'未実施'}</span><strong>${r?.result?r.result.score+'%':'—'}</strong></div>`;}).join('');
  const groups=new Map(challenges.filter(r=>r.status==='completed').map(r=>[comparisonKey(r),comparisonLabel(r)]));$('comparison-group').innerHTML=groups.size?[...groups].map(([k,l])=>`<option value="${esc(k)}" ${k===group?'selected':''}>${esc(l)}</option>`).join(''):'<option>終了した記録がありません</option>';$('comparison-group').disabled=!groups.size;
  const receipts=store.receipts(profile.code),sent=new Set(receipts.flatMap(r=>r.attemptIds)),pending=challenges.filter(a=>a.result&&!sent.has(a.attemptId));$('submission-receipt').textContent=receipts.length?`最終提出 ${new Date(receipts.at(-1).receivedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} ／ 受付番号 ${receipts.at(-1).receiptId} ／ 未提出の本チャレンジ終了記録 ${pending.length}回`:'このブラウザには提出完了の記録がありません。';const delta=v=>v==null?'—':(v>0?'+':'')+v+'ポイント';
  const assessment=challengeAssessment(challenges);$('aspect-summary').innerHTML=`<p>対象の本チャレンジ ${assessment.completed}/5回・${assessment.total}/375問${assessment.excluded?' ／ 旧条件の記録 '+assessment.excluded+'回は参考記録として除外':''}</p><div class="stats">${assessment.byAspect.map((x,i)=>`<div class="stat">${esc(x.aspect)}<strong>${x.rate==null?'—':x.rate+'%'}</strong><small>正解 ${x.correct}/${x.total}問 ／ 5回で${i===0?150:225}問・配点${i===0?40:60}点</small></div>`).join('')}<div class="stat">${assessment.final?'5回総合点':'途中の総合正答率'}<strong>${assessment.weighted==null?'—':assessment.weighted+' / 100'}</strong><small>${assessment.final?'5回終了の確定集計':'5回終了まで総合点は未確定。終了分の参考値。'}</small></div></div>`;const effort=practiceEvidence(records,getMetadata?.()??{questions:{}});$('practice-evidence').innerHTML=`<p>練習開始 ${effort.started}回 ／ 終了 ${effort.completed}回</p><div class="stats"><div class="stat">誤答への再挑戦<strong>${effort.retryUnique}問</strong><small>一度誤った問題に再び取り組んだ異なる問題数</small></div><div class="stat">誤答からの改善<strong>${effort.improvedUnique}/${effort.retryUnique}問</strong><small>${effort.improvementRate==null?'再挑戦の記録待ち':effort.improvementRate+'%が後の練習で正解'}</small></div><div class="stat">同じ弱点単元の別問題<strong>${effort.transferCorrect}/${effort.transferTotal}問</strong><small>${effort.transferTopics}単元。単元名は参考分類。</small></div></div>`;
  $('progress-summary').innerHTML=`<div class="metric"><span>最新の総合正答率</span><strong>${summary.latest==null?'—':summary.latest+'%'}</strong><small>${summary.firstRound?`第${summary.firstRound}回 → 第${summary.lastRound}回`:'受験終了後に表示'}</small><b>伸び ${summary.selected.length>1?delta(summary.gain):'比較待ち'}</b></div>`+summary.byDomain.map(d=>`<div class="metric"><span>${esc(d.domain)}</span><strong>${d.latest==null?'対象外':d.latest+'%'}</strong><small>正解 ${d.correct} / ${d.total}問</small><b>伸び ${summary.selected.length>1?delta(d.gain):'比較待ち'}</b></div>`).join('');
  visible=chartLegend($('progress-legend'),v=>drawProgressChart($('progress-chart'),selected,v));drawProgressChart($('progress-chart'),selected,visible());
  $('attempt-records').innerHTML=records.map(r=>`<tr><td>${esc(roundLabel(r))}</td><td>${isCancelled(r)?'取消し（回数対象外）':esc(STATUS_LABELS[r.status])}<br><small>受験ID：${esc(r.attemptId)}</small>${r.correction?'<br><small>理由：'+esc(r.correction.payload.reason)+'</small>':''}<br><small>${esc(new Date(r.startedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}))}</small></td><td>${esc(comparisonLabel(r))}<br><small>${esc(r.title)}</small></td><td>${r.result?`${r.result.score}% (${r.result.correct}/${r.result.total})<br><small>${ASPECTS.map(label=>{const x=r.result.byAspect?.find(x=>x.aspect===label);return esc(label)+'：'+(x?.total?x.correct+'/'+x.total+'問（'+x.rate+'%）':'未分類');}).join('<br>')}</small>`:'—'}</td>${DOMAINS.map(d=>{const b=r.result?.byDomain.find(x=>x.domain===d);return `<td>${b?.rate!=null?b.rate+'% ('+b.correct+'/'+b.total+')':'—'}</td>`;}).join('')}<td><button class="secondary" data-attempt="${r.attemptId}">${isCancelled(r)?'取消済み':r.status==='running'?'再開':'結果'}</button></td></tr>`).join('')||'<tr><td colspan="8">受験記録はまだありません。</td></tr>';
  document.querySelectorAll('[data-attempt]').forEach(b=>b.onclick=async()=>{try{const a=records.find(r=>r.attemptId===b.dataset.attempt);if(isCancelled(a)&&!a.result)throw new Error('この受験は取消済みです。表紙を再読み込みして再受験してください。');await openAttempt(a);}catch(e){message(e.message);}});
 }
 async function verifyTeacherCorrection(token){const ip=$('submit-ip').value.trim();if(!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(ip)||ip.split('.').some(x=>+x>255))throw new Error('教員修正の確認のため、提出先IPアドレスを入力してください。');const resp=await fetch(`http://${ip}:3000/api/corrections/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token),credentials:'omit',signal:AbortSignal.timeout(15000)}),reply=await resp.json();if(!resp.ok||reply.ok!==true)throw new Error(reply.error||'教員発行の確認に失敗しました。');}
 $('correction-file').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>20000)throw new Error('修正ファイルを確認してください。');const token=JSON.parse(await f.text()),c=token.payload;if(c?.studentCode!==profile.code||normalizeName(c.studentName)!==profile.name)throw new Error('同じ番号・氏名の修正ファイルを選んでください。');const ip=$('submit-ip').value.trim();if(!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(ip)||ip.split('.').some(x=>+x>255))throw new Error('提出先のIPv4アドレスを入力してください。');const resp=await fetch(`http://${ip}:3000/api/corrections/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token),credentials:'omit',signal:AbortSignal.timeout(15000)}),reply=await resp.json();if(!resp.ok||reply.ok!==true)throw new Error(reply.error||'教員発行の確認に失敗しました。');if(!confirm(`受験を取消し、使用回数を1回戻します。理由：${c.reason}。元の記録は残します。`))return;const applied=store.applyCorrection(token);if(applied)onCorrection?.();render();message(applied?'修正を保存しました。表紙を再読み込みして再受験してください。':'この修正は適用済みです。');}catch(e){message(e.message);}finally{e.target.value='';}};
 $('comparison-group').onchange=e=>{group=e.target.value;render();};new ResizeObserver(()=>{if(profile&&!$('status-screen').hidden)drawProgressChart($('progress-chart'),selected,visible());}).observe($('progress-chart'));
 $('status-json').onclick=()=>download(exportPacket(),`IPass_${profile.code}_history.json`);
 $('status-csv').onclick=()=>{const rows=[['受験番号','氏名','実施回','状態','出題条件','総合正答率',...DOMAINS,'開始日時','終了日時'],...store.forStudent(profile.code).map(r=>[profile.code,profile.name,roundLabel(r),STATUS_LABELS[r.status],comparisonLabel(r),r.result?.score??'',...DOMAINS.map(d=>r.result?.byDomain.find(x=>x.domain===d)?.rate??''),r.startedAt,r.finishedAt??''])];download(toCsv(rows),`IPass_${profile.code}_progress.csv`,'text/csv;charset=utf-8');};
 $('status-send').onclick=async()=>{const ip=$('submit-ip').value.trim();if(!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(ip)||ip.split('.').some(x=>+x>255)){message('先生から指定されたIPv4アドレスを入力してください。例：192.168.1.50');return;}if(!store.forStudent(profile.code).length){message('提出する受験記録がありません。');return;}const packet=exportPacket();$('status-send').disabled=true;message('送信中…');try{const res=await fetch(`http://${ip}:3000/api/submissions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(packet),credentials:'omit',redirect:'error',signal:AbortSignal.timeout(15000)}),r=await res.json();if(!res.ok||r.ok!==true||r.studentCode!==profile.code||typeof r.receiptId!=='string')throw new Error(r.error||'受付完了を確認できません。');try{localStorage.setItem('ipass:submit-ip',ip);store.saveReceipt(profile.code,r,packet.attempts);render();}catch(e){message(`送信は受付されましたが提出済み表示を保存できません。受付番号 ${r.receiptId} を控えてください。`);return;}message(`提出完了：受付番号 ${r.receiptId}。ブラウザの記録も残しています。`);}catch(e){message(`提出完了を確認できません。IPアドレス・サーバ起動・校内ネットワーク／ローカルネットワークのアクセス許可を確認してください。履歴JSONを保存して提出することもできます。${e.name==='TypeError'?'':' '+e.message}`);}finally{$('status-send').disabled=false;}};
 $('status-import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw new Error('ファイルが大きすぎます。');const p=JSON.parse(await file.text());if(p.app!=='info1_IPass'||p.kind!=='progress'||p.schemaVersion!==2||p.studentCode!==profile.code||normalizeName(p.studentName)!==profile.name||!Array.isArray(p.attempts)||p.attempts.length>10000)throw new Error('同じ番号・氏名の履歴JSONを選んでください。');const old=store.forStudent(profile.code),ids=new Set(),rounds=new Set(),validated=[];
  for(const a of p.attempts){if(!isUuid(a.attemptId)||ids.has(a.attemptId)||(!isCancelled(a)&&rounds.has(attemptKind(a)+':'+a.round))||!Number.isInteger(a.round)||a.round<1||a.studentCode!==profile.code||normalizeName(a.studentName)!==profile.name||!Number.isFinite(Date.parse(a.startedAt))||!['running','completed','abandoned'].includes(a.status))throw new Error('受験記録の形式が不正です。');ids.add(a.attemptId);if(!isCancelled(a))rounds.add(attemptKind(a)+':'+a.round);
   const terminal=old.find(x=>x.attemptId===a.attemptId&&x.status!=='running');if(isCancelled(a)&&a.correction?.signature!==old.find(x=>x.attemptId===a.attemptId)?.correction?.signature){await verifyTeacherCorrection(a.correction);}if(terminal){validated.push(isCancelled(a)?{...terminal,cancelled:true,correction:a.correction,result:{...terminal.result,cancelled:true,correction:a.correction}}:terminal);continue;}
   const s=a.session,r=a.result,questions=r?await loadQuestions(r.answers?.map(x=>x.id)):await loadQuestions(s?.questionIds),picked={};if(!questions.length||questions.length>1500||new Set(questions.map(q=>q.id)).size!==questions.length)throw new Error('問題IDが不正です。');
   if(r){if(r.attemptId!==a.attemptId||r.studentCode!==profile.code||normalizeName(r.studentName)!==profile.name||!Array.isArray(r.answers)||!Number.isFinite(Date.parse(r.finishedAt))||a.status==='running')throw new Error('結果形式が不正です。');for(const x of r.answers){if(!Number.isInteger(x.picked)||x.picked< -1||x.picked>3)throw new Error('解答が不正です。');if(x.picked>=0)picked[x.id]=x.picked;}a.result={...r,round:a.round,abandoned:a.status==='abandoned',...grade(questions,picked)};delete a.session;}
   else{if(a.status!=='running'||s.attemptId!==a.attemptId||s.studentCode!==profile.code||normalizeName(s.studentName)!==profile.name||s.result||!Number.isFinite(s.deadline)||!Number.isInteger(s.index)||s.index<0||s.index>=questions.length||!s.answers||!s.flags||s.startedAt!==a.startedAt)throw new Error('再開データが不正です。');for(const [id,v] of Object.entries(s.answers))if(!questions.some(q=>q.id===id)||!Number.isInteger(v)||v<0||v>3)throw new Error('再開の解答が不正です。');s.round=a.round;}
   if(old.some(x=>!isCancelled(x)&&!isCancelled(a)&&attemptKind(x)===attemptKind(a)&&x.round===a.round&&x.attemptId!==a.attemptId))throw new Error('同じ実施回に異なる記録があります。元の履歴と確認してください。');validated.push(a);
  }
  const merged=mergeAttempts(old,validated);if(merged.filter(a=>isChallenge(a)&&!isCancelled(a)).length>Math.max(MAX_ATTEMPTS,old.filter(a=>isChallenge(a)&&!isCancelled(a)).length)||merged.filter(a=>a.status==='running'&&!isCancelled(a)).length>1)throw new Error('5回を超える記録、または複数の受験中の記録があります。');store.write(mergeAttempts(store.all(),validated));const activeId=JSON.parse(localStorage.getItem('ipass:active:v1')||'null')?.attemptId;if(activeId&&validated.some(a=>a.attemptId===activeId&&isCancelled(a))){localStorage.removeItem('ipass:active:v1');onCorrection?.();}render();message('履歴を読み込みました。回数を引き継ぎ、公式解答で再採点しました。');
 }catch(err){message(err.message);}finally{e.target.value='';}};
 return {open(code,name){name=normalizeName(name);if(!validStudent(code,name))throw new Error('4桁番号と「姓 名」を入力してください。');store.checkName(code,name);profile={code,name};$('student-code').value=code;$('student-name').value=name;group=null;message('');try{$('submit-ip').value=localStorage.getItem('ipass:submit-ip')||'';}catch{}screen('status');render();},render};
}
