import {teacherStore} from './teacher-store.js';
import {buildStatistics,challengeGroups,statisticsCsv} from './statistics-model.js';
import {toCsv} from './core.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),show=n=>n==null?'—':n;
let records=[],roster=[],metadata={questions:{}},report,svg='';
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function chart(data){const width=1000,classHeight=Math.max(1,data.classes.length)*48+95,height=classHeight+640;let y=60,parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="chart-title chart-description"><title id="chart-title">${esc(data.conditions.label||'本チャレンジの集計')}</title><desc id="chart-description">クラス別最新平均、各回平均、最新得点分布。人数は各表示のn。</desc><rect width="100%" height="100%" fill="white"/><g font-family="Meiryo, Yu Gothic, sans-serif" fill="#17263c"><text x="30" y="28" font-size="19" font-weight="bold">${esc(data.conditions.label||'本チャレンジの集計')}</text><text x="30" y="48" font-size="12">${esc(data.conditions.groupLabel)} ／ ${esc(data.conditions.from||'開始指定なし')}〜${esc(data.conditions.to||'終了指定なし')} ／ ${esc(data.conditions.classCode||'全クラス')}</text><text x="30" y="${y+20}" font-size="17" font-weight="bold">クラス別の最新平均（1人1件）</text>`];y+=44;for(const c of data.classes){parts.push(`<text x="30" y="${y+20}" font-size="15">${esc(c.classCode)}クラス</text><rect x="160" y="${y}" width="${(c.latest.mean??0)*6}" height="28" rx="3" fill="#325f86"/><text x="${175+(c.latest.mean??0)*6}" y="${y+20}" font-size="14">${show(c.latest.mean)}%　n=${c.latest.n}</text>`);y+=48;}
 y=classHeight+50;parts.push(`<text x="30" y="${y}" font-size="17" font-weight="bold">各回の平均（各回の参加者は異なる場合があります）</text>`);const top=y+25,bottom=top+180;for(const n of [0,20,40,60,80,100]){const at=bottom-n*1.8;parts.push(`<line x1="110" x2="830" y1="${at}" y2="${at}" stroke="#d6dfe6"/><text x="65" y="${at+5}" font-size="12">${n}%</text>`);}let previous;for(const r of data.overall.rounds){const x=110+(r.round-1)*180,at=bottom-(r.mean??0)*1.8;parts.push(`<text x="${x-20}" y="${bottom+26}" font-size="14">第${r.round}回</text><text x="${x-20}" y="${bottom+45}" font-size="12">n=${r.n}</text>`);if(r.mean!=null){if(previous)parts.push(`<line x1="${previous.x}" y1="${previous.at}" x2="${x}" y2="${at}" stroke="#325f86" stroke-width="3"/>`);parts.push(`<circle cx="${x}" cy="${at}" r="6" fill="#325f86"/><text x="${x+10}" y="${at-8}" font-size="13">${r.mean}%</text>`);previous={x,at};}else previous=null;}
 y=bottom+90;parts.push(`<text x="30" y="${y}" font-size="17" font-weight="bold">最新得点の分布（1人1件、n=${data.overall.latest.n}）</text>`);for(const b of data.overall.distribution){y+=38;const max=Math.max(1,...data.overall.distribution.map(x=>x.count));parts.push(`<text x="30" y="${y+19}" font-size="14">${esc(b.label)}点</text><rect x="160" y="${y}" width="${b.count/max*600}" height="25" rx="3" fill="#2d806c"/><text x="${175+b.count/max*600}" y="${y+19}" font-size="14">${b.count}人</text>`);}parts.push(`<text x="30" y="${height-16}" font-size="12">未提出・中断・取消しを得点0として扱わない。出題問題・年度の難易度は異なる。観点分類は一次分類。</text></g></svg>`);return parts.join('');}
function render(){try{report=buildStatistics(roster,records,metadata,{group:$('statistics-group').value,classCode:$('statistics-class').value,from:$('statistics-from').value,to:$('statistics-to').value,label:$('statistics-label').value.trim()});const minimum=Number($('statistics-minimum').value);if(!Number.isInteger(minimum)||minimum<1||minimum>10000)throw new Error('最小解答件数は1〜10000にしてください。');report.conditions.minimumAnswers=minimum;report.topics=report.topics.filter(t=>t.total>=minimum);report.questions=report.questions.filter(q=>q.total>=minimum);const s=report.overall,p=s.practice;$('statistics-report-title').textContent=report.conditions.label||'集計結果';$('statistics-condition-note').textContent=`${report.conditions.groupLabel} ／ ${report.conditions.classCode||'全クラス'} ／ ${report.conditions.from||'開始指定なし'}〜${report.conditions.to||'終了指定なし'} ／ 問題・参考単元は解答${minimum}件以上`;
 $('statistics-summary').innerHTML=[['名簿人数',report.conditions.rosterLoaded?s.enrolled:'未読込'],['完了提出者',s.completedStudents+'人'],['最新平均',show(s.latest.mean)+'%（'+s.latest.n+'人）'],['5回総合平均',show(s.final5.mean)+'%（'+s.final5.n+'人）'],['初回→最新の平均差',show(s.paired.gain.mean)+'ポイント（'+s.paired.n+'人）']].map(([label,value])=>`<div class="stat">${esc(label)}<strong>${esc(value)}</strong></div>`).join('');
 const text=[];if(s.latest.n)text.push(`対象${s.latest.n}人の最新得点は平均${s.latest.mean}%、中央値${s.latest.median}%、標準偏差${s.latest.sd}ポイントです。`);if(s.paired.n)text.push(`同じ生徒${s.paired.n}人の初回と最新を比べた平均差は${s.paired.gain.mean}ポイントです。上昇${s.paired.improved}人、変化なし${s.paired.unchanged}人、低下${s.paired.decreased}人でした。`);if(s.round1to5.n)text.push(`第1回と第5回の両方がある${s.round1to5.n}人では、平均差は${s.round1to5.gain.mean}ポイントです。`);if(report.topics.length)text.push(`参考分類の「${report.topics[0].topic}」は正答率${report.topics[0].rate}%（解答${report.topics[0].total}件、${report.topics[0].students}人）です。次年度の指導内容や設問を確認する材料にできます。`);$('statistics-insights').innerHTML=text.map(t=>`<p>${esc(t)}</p>`).join('')||'<p>対象の完了記録はありません。</p>';$('statistics-quality').textContent=`取込記録 ${report.quality.inputRecords}件 ／ 名簿照合対象外 ${report.quality.unmatchedRecords}件 ／ 期間内 ${report.quality.periodRecords}件 ／ 取消し ${report.quality.cancelled}件 ／ 中断 ${report.quality.abandoned}件 ／ 同一回の重複整理 ${report.quality.duplicateRounds}件`;
 $('statistics-classes').innerHTML=report.classes.map(c=>`<tr><td>${esc(c.classCode)}</td><td>${report.conditions.rosterLoaded?c.enrolled:'—'}</td><td>${c.completedStudents}</td><td>${c.completed5}</td><td>${show(c.latest.mean)}／${show(c.latest.median)}／${show(c.latest.sd)} (${c.latest.n}人)</td><td>${show(c.paired.gain.mean)}ポイント (${c.paired.n}人)</td><td>${show(c.round1to5.gain.mean)}ポイント (${c.round1to5.n}人)</td></tr>`).join('')||'<tr><td colspan="7">対象なし</td></tr>';
 $('statistics-dimensions').innerHTML=[...s.byDomain.map(d=>({...d,label:d.domain})),...s.byAspect.map(a=>({...a,label:a.aspect})),{...s.final5,label:'5回総合（条件適合者）'}].map(x=>`<tr><td>${esc(x.label)}</td><td>${x.n}</td><td>${show(x.mean)}</td><td>${show(x.median)}</td><td>${show(x.sd)}</td><td>${show(x.min)}</td><td>${show(x.max)}</td></tr>`).join('');
 $('statistics-practice').innerHTML=[['練習提出者',p.participants+'人'],['練習終了',p.completed+'回'],['終了回数の平均',show(p.attempts.mean)+'回（'+p.attempts.n+'人）'],['誤答への再挑戦',p.retryProblems+'問（'+p.improvementStudents+'人）'],['誤答からの改善',p.improvedProblems+'/'+p.retryProblems+'問'],['苦手単元の別問題',p.transferCorrect+'/'+p.transferTotal+'問']].map(([k,v])=>`<div class="stat">${esc(k)}<strong>${esc(v)}</strong></div>`).join('');
 $('statistics-topics').innerHTML=report.topics.map(t=>`<tr><td>${esc(t.topic)}</td><td>${t.students}</td><td>${t.total}</td><td>${t.correct}</td><td>${t.unanswered}</td><td>${t.rate}%</td></tr>`).join('')||'<tr><td colspan="6">最小解答件数を満たす単元がありません。</td></tr>';
 $('statistics-questions').innerHTML=report.questions.slice(0,30).map(q=>`<tr><td>${esc(q.id)}<br><small>${esc(q.source)}</small></td><td>${esc(q.domain)}</td><td>${q.students}</td><td>${q.total}</td><td>${q.unanswered}</td><td>${q.rate}%</td></tr>`).join('')||'<tr><td colspan="6">最小解答件数を満たす問題がありません。</td></tr>';$('statistics-notes').innerHTML=report.notes.map(n=>`<li>${esc(n)}</li>`).join('');svg=chart(report);$('statistics-chart').innerHTML=svg;for(const id of ['statistics-csv','statistics-json','statistics-svg','statistics-print'])$(id).disabled=false;$('statistics-message').textContent=metadata.unavailable?'参考単元データを取得できません。単元集計は分野単位の参考表示です。':'';
 }catch(e){for(const id of ['statistics-csv','statistics-json','statistics-svg','statistics-print'])$(id).disabled=true;$('statistics-message').textContent=e.message;}}
for(const id of ['statistics-label','statistics-class','statistics-group','statistics-from','statistics-to','statistics-minimum'])$(id).onchange=render;
$('statistics-csv').onclick=()=>download(toCsv(statisticsCsv(report)),'IPass_statistics.csv','text/csv;charset=utf-8');$('statistics-json').onclick=()=>download(JSON.stringify(report,null,2),'IPass_statistics.json','application/json');$('statistics-svg').onclick=()=>download(svg,'IPass_statistics_charts.svg','image/svg+xml;charset=utf-8');$('statistics-print').onclick=()=>window.print();
async function load(){try{records=await teacherStore.records();roster=await teacherStore.roster();const keepClass=$('statistics-class').value||new URLSearchParams(location.search).get('class')||'',keepGroup=$('statistics-group').value,classes=[...new Set((roster.length?roster.map(p=>p.code):records.map(r=>r.studentCode)).map(c=>c.slice(0,2)))].sort(),groups=challengeGroups(records);$('statistics-class').innerHTML='<option value="">全クラス</option>'+classes.map(c=>`<option value="${esc(c)}">${esc(c)}クラス</option>`).join('');$('statistics-class').value=classes.includes(keepClass)?keepClass:'';$('statistics-group').innerHTML=groups.length?groups.map(g=>`<option value="${esc(g.key)}">${esc(g.label)}</option>`).join(''):'<option value="">完了記録がありません</option>';$('statistics-group').value=groups.some(g=>g.key===keepGroup)?keepGroup:groups.at(-1)?.key??'';try{const r=await fetch('data/question-meta.json');if(!r.ok)throw new Error();metadata=await r.json();}catch{metadata={questions:{},unavailable:true};}render();}catch(e){$('statistics-message').textContent=e.message;}}
$('statistics-refresh').onclick=load;await load();
