const $=id=>document.getElementById(id);
let mode='login';
const allowed=new Set(['/admin.html','/compare.html','/analytics.html','/aspect-review.html','/audit.html']);
const next=new URLSearchParams(location.search).get('next'),destination=allowed.has(next)?next:'admin.html';
const message=s=>$('login-message').textContent=s;
async function post(action,body){const r=await fetch('api/teacher-auth/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),credentials:'same-origin',cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error||'認証に失敗しました。');return data;}
function form(kind){mode=kind;$('teacher-login').hidden=false;$('signed-in').hidden=true;$('login-title').textContent=kind==='setup'?'初回のパスワード設定':kind==='change'?'パスワードを変更':'ログイン';$('login-submit').textContent=kind==='login'?'ログイン':'設定して教員画面へ';$('current-label').hidden=kind!=='change';$('current-password').required=kind==='change';$('confirm-label').hidden=kind==='login';$('confirm-password').required=kind!=='login';$('teacher-password').minLength=kind==='login'?1:8;$('teacher-password').autocomplete=kind==='login'?'current-password':'new-password';}
$('teacher-login').onsubmit=async e=>{e.preventDefault();$('login-submit').disabled=true;try{const password=$('teacher-password').value;if(mode!=='login'&&password!==$('confirm-password').value)throw new Error('確認用のパスワードが一致しません。');await post(mode,{password,currentPassword:$('current-password').value});$('teacher-login').reset();location.replace(destination);}catch(e){message(e.message);}finally{$('login-submit').disabled=false;}};
$('change-password').onclick=()=>{message('現在のパスワードと新しいパスワードを入力してください。');form('change');};
$('teacher-logout').onclick=async()=>{try{await post('logout',{});const channel=new BroadcastChannel('ipass-teacher-auth');channel.postMessage('logout');channel.close();location.reload();}catch(e){message(e.message);}};
try{const r=await fetch('api/teacher-auth/status',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error();const state=await r.json();if(typeof state.configured!=='boolean'||typeof state.authenticated!=='boolean')throw new Error();if(state.authenticated){message('教員としてログインしています。');$('signed-in').hidden=false;}else{form(state.configured?'login':'setup');message(state.configured?'教員用パスワードを入力してください。':'学校サーバPCで、先生が使用するパスワードを設定してください。');}}catch{message('公開サイトでは教員用の設定・成績画面を開けません。学校サーバを起動し、サーバPCで http://localhost:3000/admin.html を開いてパスワードを設定・入力してください。');}
