import test from 'node:test';
import assert from 'node:assert/strict';
import {issueCorrection,verifyCorrection} from '../local-server/correction-auth.mjs';
import {StudentStore} from '../student-store.js';
import {mergeAttempts,progressPacket} from '../progress.js';
import {classSummary,questionSummary,uniqueResults} from '../analytics-model.js';
import {DOMAINS,grade} from '../core.js';
import {validateSubmission} from '../submission-validation.js';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,base={studentCode:'1101',studentName:'岡田 太郎',title:'test',settings:{mode:'school',count:75,minutes:45,domain:'all'},startedAt:'2026-10-01T00:00:00Z',finishedAt:'2026-10-01T00:01:00Z'},bank=[{id:'q-1',domain:DOMAINS[0],answer:0},{id:'q-2',domain:DOMAINS[1],answer:0}];
function result(n,correct=true){return {...base,app:'info1_IPass',schemaVersion:1,attemptId:id(n),round:n,...grade(bank,correct?{'q-1':0,'q-2':0}:{})};}
function record(n){return {...base,attemptId:id(n),round:n,kind:'challenge',status:'completed',result:result(n)};}
const token=n=>issueCorrection({app:'info1_IPass',kind:'correction',schemaVersion:1,action:'cancel',correctionId:id(100+n),studentCode:base.studentCode,studentName:base.studentName,attemptId:id(n),reason:'端末故障',issuedAt:base.startedAt},'test-key');
function browser(){const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});return mem;}
test('教員修正の署名は内容改変・異なる鍵を拒否',()=>{const t=token(1);assert.equal(verifyCorrection(t,'test-key').attemptId,id(1));assert.throws(()=>verifyCorrection({...t,payload:{...t.payload,attemptId:id(2)}},'test-key'));assert.throws(()=>verifyCorrection(t,'other-key'));});
test('5回終了後の取消しは元記録を保持して1枠を戻し、再適用で増やさない',async()=>{browser();const store=new StudentStore();store.write([1,2,3,4,5].map(record));assert.equal(store.nextRound(base.studentCode,{mode:'school'}),6);assert.equal(store.applyCorrection(token(3)),true);assert.equal(store.applyCorrection(token(3)),false);assert.equal(store.forStudent(base.studentCode).length,5);assert.equal(store.challengeFor(base.studentCode).length,4);assert.equal(store.nextRound(base.studentCode,{mode:'school'}),3);const replacement=await store.start({...base,attemptId:id(6),minutes:45,questionIds:['q-1'],answers:{},flags:{},index:0});assert.equal(replacement.round,3);assert.equal(store.challengeFor(base.studentCode).length,5);assert.equal(store.all().find(a=>a.attemptId===id(3)).correction.payload.reason,'端末故障');assert.equal(mergeAttempts(store.all()).find(a=>a.attemptId===id(6)).round,3);});
test('取消しと再受験の同じ回を提出できるが未取消しの重複回は拒否',()=>{const a=record(1);a.cancelled=true;a.correction=token(1);const b={...record(2),round:1};const p=progressPacket([a,b],base.studentCode,base.studentName);assert.equal(validateSubmission(p,new Map(bank.map(q=>[q.id,q]))).length,2);delete a.cancelled;assert.throws(()=>validateSubmission(progressPacket([a,b],base.studentCode,base.studentName),new Map(bank.map(q=>[q.id,q]))));});
test('提出済み表示は再読込後も保存され、同じ受付を重複記録しない',()=>{browser();const s=new StudentStore();const receipt={receiptId:id(200),receivedAt:base.finishedAt};s.saveReceipt(base.studentCode,receipt,[record(1)]);s.saveReceipt(base.studentCode,receipt,[record(1)]);const loaded=new StudentStore();assert.equal(loaded.receipts(base.studentCode).length,1);assert.deepEqual(loaded.receipts(base.studentCode)[0].attemptIds,[id(1)]);});
test('保存失敗は例外とエラー状態を残す',()=>{browser();const s=new StudentStore();globalThis.localStorage.setItem=()=>{throw new Error('quota');};assert.throws(()=>s.write([record(1)]));assert.match(s.error,/保存に失敗/);});
test('クラス集計は最新1件・名簿一致・中断取消し除外・未提出0点化なし',()=>{const a=result(1,false),b=result(2),cancelled={...result(3,false),cancelled:true},abandoned={...result(4,false),abandoned:true},mismatch={...result(5,false),studentName:'別の 人'};const c=classSummary([{code:'1101',name:base.studentName},{code:'1102',name:'佐藤 花子'}],[a,b,cancelled,abandoned,mismatch])[0];assert.equal(c.enrolled,2);assert.equal(c.submitted,1);assert.equal(c.latestCount,1);assert.equal(c.latestAverage,100);assert.equal(c.averageGain,100);});
test('問題別集計は未解答も母数、選択肢数・モード分離・重複ID整理',()=>{const a=result(1),b=result(2,false),practice={...result(3),settings:{mode:'practice'}},cancelled={...result(4),cancelled:true},abandoned={...result(5),abandoned:true};const q=questionSummary([a,a,b,practice,cancelled,abandoned]);assert.equal(q[0].total,2);assert.equal(q[0].correct,1);assert.equal(q[0].unanswered,1);assert.equal(q[0].students,1);assert.equal(q[0].rate,50);assert.deepEqual(q[0].choices,[1,0,0,0]);assert.equal(questionSummary([a,practice],{mode:'practice'})[0].total,1);assert.throws(()=>uniqueResults([a,{...a,studentCode:'1102'}]));});
