import test from 'node:test';import assert from 'node:assert/strict';
import {domainAllocation,selectQuestions,DOMAINS,grade} from '../core.js';
import {mergeAttempts,summarize,comparisonKey,progressPacket} from '../progress.js';
import {validateSubmission} from '../submission-validation.js';
import {StudentStore} from '../student-store.js';
const bank=DOMAINS.flatMap((domain,d)=>Array.from({length:60},(_,i)=>({id:`q-${d}-${i}`,domain,answer:0}))),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const base={studentCode:'1215',studentName:'岡田 太郎',title:'テスト',settings:{mode:'school',count:35,minutes:40,domain:'all'},startedAt:'2026-09-30T00:00:00Z'};
function record(n,answers,status='completed'){return {...base,attemptId:id(n),round:n,status,finishedAt:'2026-09-30T00:10:00Z',result:{...base,app:'info1_IPass',schemaVersion:1,attemptId:id(n),finishedAt:'2026-09-30T00:10:00Z',...grade(bank.slice(0,2),answers)}};}
test('IPA比率と端数処理、重複なしの抽出',()=>{for(const [n,counts] of [[10,[3,2,5]],[35,[12,7,16]],[100,[35,20,45]]]){assert.deepEqual(domainAllocation(n).map(x=>x.count),counts);const qs=selectQuestions(bank,{count:n,mode:'school',domain:'all'},()=>.25);assert.equal(new Set(qs.map(x=>x.id)).size,n);assert.deepEqual(DOMAINS.map(d=>qs.filter(q=>q.domain===d).length),counts);}assert.deepEqual(selectQuestions(bank,{mode:'year'}),bank);});
test('終了記録を受験中に戻さず旧履歴に回数を割り振る',()=>{const done=record(1,{}),running={...done,status:'running',result:null,session:{fake:true}},merged=mergeAttempts([running],[done],[running]);assert.equal(merged.length,1);assert.equal(merged[0].status,'completed');assert.equal(merged[0].session,undefined);const old={...record(2,{}),round:undefined};assert.equal(mergeAttempts([done,old])[1].round,2);});
test('比較条件と中断除外、対象外分野の扱い',()=>{const a=record(1,{}),b=record(2,{'q-0-0':0}),c=record(3,{},'abandoned'),d={...record(4,{}),settings:{...base.settings,minutes:20}};const s=summarize([a,b,c,d],comparisonKey(a));assert.equal(s.selected.length,2);assert.equal(s.gain,50);assert.equal(s.byDomain[1].latest,null);assert.equal(s.byDomain[1].gain,null);});
test('提出は公式再採点し、受験番号・ID・回数・解答重複を検証',()=>{const a=record(1,{'q-0-0':0});a.result.score=100;const p=progressPacket([a],base.studentCode,base.studentName),map=new Map(bank.map(q=>[q.id,q]));assert.equal(validateSubmission(p,map)[0].score,50);assert.throws(()=>validateSubmission({...p,attempts:[a,a]},map));assert.throws(()=>validateSubmission({...p,studentCode:'1216'},map));const invalid=structuredClone(p);invalid.attempts[0].result.answers.push(invalid.attempts[0].result.answers[0]);assert.throws(()=>validateSubmission(invalid,map));});
test('ブラウザだけで5回、再開で増加せず中断も1回、名前の取り違え防止',async()=>{Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v)};const store=new StudentStore();for(let n=1;n<=5;n++){const s=await store.start({...base,attemptId:id(n),minutes:40,questionIds:['q-0-0'],answers:{},flags:{},index:0});assert.equal(s.round,n);store.record(s);assert.equal(store.forStudent('1215').length,n);await assert.rejects(()=>store.start({...s,attemptId:id(99)}));s.result={...record(n,{}).result,abandoned:n===2};store.record(s);}await assert.rejects(()=>store.start({...base,attemptId:id(6)}),/5回/);assert.equal(store.forStudent('1215')[1].status,'abandoned');assert.throws(()=>store.checkName('1215','別の 氏名'));});
