import test from 'node:test';import assert from 'node:assert/strict';
import {buildStatistics,descriptive,statisticsCsv} from '../statistics-model.js';import {comparisonKey} from '../progress.js';
const settings={mode:'school',count:75,minutes:45,domain:'all'},key=comparisonKey({settings}),roster=[{code:'1101',name:'岡田 太郎'},{code:'1102',name:'佐藤 花子'},{code:'1201',name:'田中 一郎'}];let serial=0;
function result(code,round,score,extra={}){const answers=Array.from({length:75},(_,n)=>({id:'q-'+n,domain:'ストラテジ系',aspect:n<30?'知識・技能':'思考・判断・表現',correct:n<Math.round(score*75/100),picked:n<Math.round(score*75/100)?0:-1,source:'公開問題'}));return {attemptId:'attempt-'+(++serial),studentCode:code,studentName:roster.find(p=>p.code===code)?.name??'名簿 外',round,score,total:75,correct:answers.filter(a=>a.correct).length,answers,byDomain:[{domain:'ストラテジ系',rate:score,total:75}],settings,startedAt:`2026-10-01T00:0${round}:00Z`,finishedAt:`2026-10-01T00:0${round}:30Z`,...extra};}
test('記述統計は未集計をnullとし、中央値と母標準偏差を計算する',()=>{assert.deepEqual(descriptive([]),{n:0,mean:null,median:null,sd:null,min:null,max:null});assert.deepEqual(descriptive([20,100]),{n:2,mean:60,median:60,sd:40,min:20,max:100});assert.equal(descriptive([10,30,20]).median,20);});
test('クラス統計は最新1人1件・同一条件のペア・名簿一致で比較し、未提出を0点にしない',()=>{const a=result('1101',1,20),b=result('1101',2,80),c=result('1102',1,100),rows=[a,b,b,c,result('1101',3,0,{cancelled:true}),result('1101',4,0,{abandoned:true}),result('1101',5,0,{studentName:'別の 名前'}),result('9999',1,0),result('1101',3,0,{settings:{...settings,minutes:90}}),result('1101',4,0,{settings:{...settings,mode:'practice'}})];const report=buildStatistics(roster,rows,undefined,{group:key});assert.equal(report.overall.latest.n,2);assert.equal(report.overall.latest.mean,90);assert.equal(report.overall.paired.n,1);assert.equal(report.overall.paired.gain.mean,60);assert.equal(report.overall.round1to5.n,0);assert.equal(report.classes[1].enrolled,1);assert.equal(report.classes[1].latest.mean,null);assert.equal(report.quality.unmatchedRecords,2);assert.equal(report.overall.completedAttempts,3);assert.equal(report.overall.practice.participants,1);assert.equal(report.overall.distribution.reduce((n,b)=>n+b.count,0),2);});
test('期間は終了日の日本時間で判定し、日付やクラスの絞り込みを反映する',()=>{const records=[result('1101',1,20,{finishedAt:'2026-09-30T14:59:59Z'}),result('1101',2,80,{finishedAt:'2026-09-30T15:00:00Z'}),result('1101',3,0,{finishedAt:'2026-10-01T15:00:00Z'}),result('1201',1,100,{finishedAt:'2026-10-01T02:00:00Z'})];const r=buildStatistics(roster,records,undefined,{group:key,classCode:'11',from:'2026-10-01',to:'2026-10-01'});assert.equal(r.overall.completedAttempts,1);assert.equal(r.overall.latest.mean,80);assert.equal(r.overall.paired.n,0);assert.equal(r.overall.enrolled,2);assert.equal(r.classes.length,1);assert.throws(()=>buildStatistics(roster,records,undefined,{from:'2026-10-02',to:'2026-10-01'}),/終了日/);assert.throws(()=>buildStatistics(roster,records,undefined,{from:'2026-02-30'}),/日付/);});
test('5回総合は375問かつ30／45の対象者だけ・同一回の別IDは最新1件に整理する',()=>{const rows=[1,2,3,4,5].map(n=>result('1101',n,100));const invalid=[1,2,3,4,5].map(n=>result('1102',n,100));invalid[0].answers.forEach(a=>a.aspect='知識・技能');const replacement=result('1101',1,0,{finishedAt:'2026-10-01T00:10:00Z'});const report=buildStatistics(roster,[...rows,...invalid,replacement],undefined,{group:key});assert.equal(report.quality.duplicateRounds,1);assert.equal(report.overall.completed5,2);assert.equal(report.overall.final5.n,1);assert.equal(report.overall.final5.mean,80);assert.equal(report.overall.latest.mean,50);assert.equal(report.overall.paired.n,2);assert.equal(report.overall.round1to5.n,2);});
test('匿名CSV／JSONに生徒名・番号・受験IDを含めず、未解答を問題の母数に含める',()=>{const a=result('1101',1,0),b=result('1102',1,100),report=buildStatistics(roster,[a,b],{questions:{'q-0':{topicId:'network',topic:'ネットワーク'}}},{group:key,label:'2026年度'}),json=JSON.stringify(report),csv=JSON.stringify(statisticsCsv(report));for(const text of [json,csv]){for(const privateValue of ['岡田 太郎','佐藤 花子','1101','1102',a.attemptId,b.attemptId])assert.equal(text.includes(privateValue),false);assert.equal(text.includes('studentCode'),false);}const q=report.questions.find(q=>q.id==='q-0');assert.equal(q.total,2);assert.equal(q.unanswered,1);assert.equal(q.rate,50);assert.equal(report.topics.find(t=>t.topicId==='network').students,2);});
test('名簿なしでも提出記録の統計を出し、名簿人数の不明を出力に残す',()=>{const report=buildStatistics([],[result('1101',1,80)],undefined,{group:key});assert.equal(report.conditions.rosterLoaded,false);assert.equal(report.overall.latest.n,1);const csv=statisticsCsv(report);assert.equal(csv.find(r=>r[0]==='クラス'&&r[1]==='名簿人数')[4],'');});
